-- Auto-generated by scripts/generate_print_axioms.py
-- Runs #print axioms on all top-level theorems/lemmas in proof directories.
-- Regenerate with: python3 scripts/generate_print_axioms.py

import Verity.Proofs.Counter.Basic
import Verity.Proofs.Counter.Correctness
import Verity.Proofs.ERC20.Basic
import Verity.Proofs.ERC20.Correctness
import Verity.Proofs.ERC721.Basic
import Verity.Proofs.ERC721.Correctness
import Verity.Proofs.Ledger.Basic
import Verity.Proofs.Ledger.Conservation
import Verity.Proofs.Ledger.Correctness
import Verity.Proofs.Owned.Basic
import Verity.Proofs.Owned.Correctness
import Verity.Proofs.OwnedCounter.Basic
import Verity.Proofs.OwnedCounter.Correctness
import Verity.Proofs.OwnedCounter.Isolation
import Verity.Proofs.SafeCounter.Basic
import Verity.Proofs.SafeCounter.Correctness
import Verity.Proofs.SimpleStorage.Basic
import Verity.Proofs.SimpleStorage.Correctness
import Verity.Proofs.SimpleToken.Basic
import Verity.Proofs.SimpleToken.Correctness
import Verity.Proofs.SimpleToken.Isolation
import Verity.Proofs.SimpleToken.Supply
import Verity.Proofs.Stdlib.Automation
import Verity.Proofs.Stdlib.ListSum
import Verity.Proofs.Stdlib.MappingAutomation
import Verity.Proofs.Stdlib.Math
import Compiler.Proofs.ArithmeticProfile
import Compiler.Proofs.EndToEnd
import Compiler.Proofs.IRGeneration.IRInterpreter
import Compiler.Proofs.MappingSlot
import Compiler.Proofs.SemanticBridge
import Compiler.Proofs.YulGeneration.Builtins
import Compiler.Proofs.YulGeneration.Equivalence

-- Verity/Proofs/Counter/Basic.lean
#print axioms Verity.Proofs.Counter.setStorage_updates_count
#print axioms Verity.Proofs.Counter.getStorage_reads_count
#print axioms Verity.Proofs.Counter.setStorage_preserves_other_slots
#print axioms Verity.Proofs.Counter.setStorage_preserves_context
#print axioms Verity.Proofs.Counter.setStorage_preserves_addr_storage
#print axioms Verity.Proofs.Counter.setStorage_preserves_map_storage
#print axioms Verity.Proofs.Counter.increment_meets_spec
#print axioms Verity.Proofs.Counter.increment_adds_one
#print axioms Verity.Proofs.Counter.decrement_meets_spec
#print axioms Verity.Proofs.Counter.decrement_subtracts_one
#print axioms Verity.Proofs.Counter.getCount_meets_spec
#print axioms Verity.Proofs.Counter.getCount_reads_count_value
#print axioms Verity.Proofs.Counter.increment_getCount_correct
#print axioms Verity.Proofs.Counter.decrement_getCount_correct
#print axioms Verity.Proofs.Counter.increment_twice_adds_two
#print axioms Verity.Proofs.Counter.increment_decrement_cancel
#print axioms Verity.Proofs.Counter.increment_preserves_wellformedness
#print axioms Verity.Proofs.Counter.decrement_preserves_wellformedness
#print axioms Verity.Proofs.Counter.getCount_preserves_state

-- Verity/Proofs/Counter/Correctness.lean
#print axioms Verity.Proofs.Counter.Correctness.increment_state_preserved_except_count
#print axioms Verity.Proofs.Counter.Correctness.decrement_state_preserved_except_count
#print axioms Verity.Proofs.Counter.Correctness.getCount_state_preserved
#print axioms Verity.Proofs.Counter.Correctness.increment_getCount_meets_spec
#print axioms Verity.Proofs.Counter.Correctness.decrement_getCount_meets_spec
#print axioms Verity.Proofs.Counter.Correctness.two_increments_meets_spec
#print axioms Verity.Proofs.Counter.Correctness.increment_decrement_meets_cancel
#print axioms Verity.Proofs.Counter.Correctness.getCount_preserves_wellformedness
#print axioms Verity.Proofs.Counter.Correctness.decrement_at_zero_wraps_max

-- Verity/Proofs/ERC20/Basic.lean
#print axioms Verity.Proofs.ERC20.constructor_meets_spec
#print axioms Verity.Proofs.ERC20.approve_meets_spec
#print axioms Verity.Proofs.ERC20.balanceOf_meets_spec
#print axioms Verity.Proofs.ERC20.allowanceOf_meets_spec
#print axioms Verity.Proofs.ERC20.totalSupply_meets_spec
#print axioms Verity.Proofs.ERC20.getOwner_meets_spec
-- #print axioms Verity.Proofs.ERC20.mint_unfold  -- private
#print axioms Verity.Proofs.ERC20.mint_meets_spec_when_owner
#print axioms Verity.Proofs.ERC20.mint_increases_balance_when_owner
#print axioms Verity.Proofs.ERC20.mint_increases_supply_when_owner
-- #print axioms Verity.Proofs.ERC20.transfer_unfold_self  -- private
-- #print axioms Verity.Proofs.ERC20.transfer_unfold_other  -- private
#print axioms Verity.Proofs.ERC20.transfer_meets_spec_when_sufficient
#print axioms Verity.Proofs.ERC20.transfer_decreases_sender_balance_when_sufficient
#print axioms Verity.Proofs.ERC20.transfer_increases_recipient_balance_when_sufficient

-- Verity/Proofs/ERC20/Correctness.lean
#print axioms Verity.Proofs.ERC20.balanceOf_preserves_state
#print axioms Verity.Proofs.ERC20.allowanceOf_preserves_state
#print axioms Verity.Proofs.ERC20.getTotalSupply_preserves_state
#print axioms Verity.Proofs.ERC20.getOwner_preserves_state
#print axioms Verity.Proofs.ERC20.approve_is_balance_neutral_holds
#print axioms Verity.Proofs.ERC20.transfer_preserves_totalSupply_when_sufficient
#print axioms Verity.Proofs.ERC20.transfer_preserves_owner_when_sufficient

-- Verity/Proofs/ERC721/Basic.lean
#print axioms Verity.Proofs.ERC721.constructor_meets_spec
#print axioms Verity.Proofs.ERC721.balanceOf_meets_spec
#print axioms Verity.Proofs.ERC721.ownerOf_meets_spec
#print axioms Verity.Proofs.ERC721.getApproved_meets_spec
#print axioms Verity.Proofs.ERC721.isApprovedForAll_meets_spec
#print axioms Verity.Proofs.ERC721.setApprovalForAll_meets_spec

-- Verity/Proofs/ERC721/Correctness.lean
#print axioms Verity.Proofs.ERC721.balanceOf_preserves_state
#print axioms Verity.Proofs.ERC721.ownerOf_preserves_state
#print axioms Verity.Proofs.ERC721.getApproved_preserves_state
#print axioms Verity.Proofs.ERC721.isApprovedForAll_preserves_state
#print axioms Verity.Proofs.ERC721.setApprovalForAll_is_balance_neutral_holds

-- Verity/Proofs/Ledger/Basic.lean
#print axioms Verity.Proofs.Ledger.getBalance_meets_spec
#print axioms Verity.Proofs.Ledger.getBalance_returns_balance
#print axioms Verity.Proofs.Ledger.getBalance_preserves_state
-- #print axioms Verity.Proofs.Ledger.deposit_unfold  -- private
#print axioms Verity.Proofs.Ledger.deposit_meets_spec
#print axioms Verity.Proofs.Ledger.deposit_increases_balance
#print axioms Verity.Proofs.Ledger.deposit_preserves_other_balances
-- #print axioms Verity.Proofs.Ledger.withdraw_unfold  -- private
#print axioms Verity.Proofs.Ledger.withdraw_meets_spec
#print axioms Verity.Proofs.Ledger.withdraw_decreases_balance
#print axioms Verity.Proofs.Ledger.withdraw_reverts_insufficient
-- #print axioms Verity.Proofs.Ledger.transfer_unfold_self  -- private
-- #print axioms Verity.Proofs.Ledger.transfer_unfold_other  -- private
#print axioms Verity.Proofs.Ledger.transfer_meets_spec
#print axioms Verity.Proofs.Ledger.transfer_self_preserves_balance
#print axioms Verity.Proofs.Ledger.transfer_decreases_sender
#print axioms Verity.Proofs.Ledger.transfer_increases_recipient
#print axioms Verity.Proofs.Ledger.transfer_reverts_insufficient
#print axioms Verity.Proofs.Ledger.transfer_reverts_recipient_overflow
#print axioms Verity.Proofs.Ledger.deposit_preserves_non_mapping
#print axioms Verity.Proofs.Ledger.withdraw_preserves_non_mapping
#print axioms Verity.Proofs.Ledger.deposit_preserves_wellformedness
#print axioms Verity.Proofs.Ledger.withdraw_preserves_wellformedness
#print axioms Verity.Proofs.Ledger.deposit_getBalance_correct

-- Verity/Proofs/Ledger/Conservation.lean
#print axioms Verity.Proofs.Ledger.Conservation.deposit_sum_equation
#print axioms Verity.Proofs.Ledger.Conservation.deposit_sum_singleton_sender
#print axioms Verity.Proofs.Ledger.Conservation.withdraw_sum_equation
#print axioms Verity.Proofs.Ledger.Conservation.withdraw_sum_singleton_sender
#print axioms Verity.Proofs.Ledger.Conservation.transfer_sum_equation
#print axioms Verity.Proofs.Ledger.Conservation.transfer_sum_preserved_unique
#print axioms Verity.Proofs.Ledger.Conservation.deposit_withdraw_sum_cancel

-- Verity/Proofs/Ledger/Correctness.lean
#print axioms Verity.Proofs.Ledger.Correctness.transfer_preserves_wellformedness
#print axioms Verity.Proofs.Ledger.Correctness.transfer_preserves_non_mapping
#print axioms Verity.Proofs.Ledger.Correctness.withdraw_getBalance_correct
#print axioms Verity.Proofs.Ledger.Correctness.transfer_getBalance_sender_correct
#print axioms Verity.Proofs.Ledger.Correctness.transfer_getBalance_recipient_correct
#print axioms Verity.Proofs.Ledger.Correctness.deposit_withdraw_cancel

-- Verity/Proofs/Owned/Basic.lean
#print axioms Verity.Proofs.Owned.setStorageAddr_updates_owner
#print axioms Verity.Proofs.Owned.getStorageAddr_reads_owner
#print axioms Verity.Proofs.Owned.setStorageAddr_preserves_other_slots
#print axioms Verity.Proofs.Owned.setStorageAddr_preserves_uint_storage
#print axioms Verity.Proofs.Owned.setStorageAddr_preserves_map_storage
#print axioms Verity.Proofs.Owned.setStorageAddr_preserves_context
#print axioms Verity.Proofs.Owned.constructor_meets_spec
#print axioms Verity.Proofs.Owned.constructor_sets_owner
#print axioms Verity.Proofs.Owned.getOwner_meets_spec
#print axioms Verity.Proofs.Owned.getOwner_returns_owner
#print axioms Verity.Proofs.Owned.getOwner_preserves_state
#print axioms Verity.Proofs.Owned.isOwner_meets_spec
#print axioms Verity.Proofs.Owned.isOwner_returns_correct_value
#print axioms Verity.Proofs.Owned.transferOwnership_unfold
#print axioms Verity.Proofs.Owned.transferOwnership_meets_spec_when_owner
#print axioms Verity.Proofs.Owned.transferOwnership_changes_owner_when_allowed
#print axioms Verity.Proofs.Owned.constructor_getOwner_correct
#print axioms Verity.Proofs.Owned.constructor_preserves_wellformedness
#print axioms Verity.Proofs.Owned.getOwner_preserves_wellformedness

-- Verity/Proofs/Owned/Correctness.lean
#print axioms Verity.Proofs.Owned.Correctness.transferOwnership_reverts_when_not_owner
#print axioms Verity.Proofs.Owned.Correctness.transferOwnership_preserves_wellformedness
#print axioms Verity.Proofs.Owned.Correctness.constructor_transferOwnership_getOwner
#print axioms Verity.Proofs.Owned.Correctness.transferred_owner_cannot_act

-- Verity/Proofs/OwnedCounter/Basic.lean
-- #print axioms Verity.Proofs.OwnedCounter.onlyOwner_reverts  -- private
-- #print axioms Verity.Proofs.OwnedCounter.guarded_reverts  -- private
#print axioms Verity.Proofs.OwnedCounter.constructor_meets_spec
#print axioms Verity.Proofs.OwnedCounter.constructor_sets_owner
#print axioms Verity.Proofs.OwnedCounter.constructor_preserves_count
#print axioms Verity.Proofs.OwnedCounter.getCount_meets_spec
#print axioms Verity.Proofs.OwnedCounter.getCount_returns_count
#print axioms Verity.Proofs.OwnedCounter.getCount_preserves_state
#print axioms Verity.Proofs.OwnedCounter.getOwner_meets_spec
#print axioms Verity.Proofs.OwnedCounter.getOwner_returns_owner
#print axioms Verity.Proofs.OwnedCounter.getOwner_preserves_state
#print axioms Verity.Proofs.OwnedCounter.isOwner_correct
#print axioms Verity.Proofs.OwnedCounter.increment_unfold
#print axioms Verity.Proofs.OwnedCounter.increment_meets_spec_when_owner
#print axioms Verity.Proofs.OwnedCounter.increment_adds_one_when_owner
#print axioms Verity.Proofs.OwnedCounter.increment_reverts_when_not_owner
#print axioms Verity.Proofs.OwnedCounter.decrement_unfold
#print axioms Verity.Proofs.OwnedCounter.decrement_meets_spec_when_owner
#print axioms Verity.Proofs.OwnedCounter.decrement_subtracts_one_when_owner
#print axioms Verity.Proofs.OwnedCounter.decrement_reverts_when_not_owner
#print axioms Verity.Proofs.OwnedCounter.transferOwnership_unfold
#print axioms Verity.Proofs.OwnedCounter.transferOwnership_meets_spec_when_owner
#print axioms Verity.Proofs.OwnedCounter.transferOwnership_changes_owner
#print axioms Verity.Proofs.OwnedCounter.transferOwnership_reverts_when_not_owner
#print axioms Verity.Proofs.OwnedCounter.increment_preserves_owner
#print axioms Verity.Proofs.OwnedCounter.decrement_preserves_owner
#print axioms Verity.Proofs.OwnedCounter.transferOwnership_preserves_count
#print axioms Verity.Proofs.OwnedCounter.constructor_preserves_wellformedness
#print axioms Verity.Proofs.OwnedCounter.increment_preserves_wellformedness
#print axioms Verity.Proofs.OwnedCounter.decrement_preserves_wellformedness
#print axioms Verity.Proofs.OwnedCounter.constructor_increment_getCount

-- Verity/Proofs/OwnedCounter/Correctness.lean
-- #print axioms Verity.Proofs.OwnedCounter.Correctness.transfer_sender_not_new_owner  -- private
#print axioms Verity.Proofs.OwnedCounter.Correctness.transfer_then_increment_reverts
#print axioms Verity.Proofs.OwnedCounter.Correctness.transfer_then_decrement_reverts
#print axioms Verity.Proofs.OwnedCounter.Correctness.transfer_then_transfer_reverts
#print axioms Verity.Proofs.OwnedCounter.Correctness.transferOwnership_preserves_wellformedness
#print axioms Verity.Proofs.OwnedCounter.Correctness.increment_survives_transfer

-- Verity/Proofs/OwnedCounter/Isolation.lean
#print axioms Verity.Proofs.OwnedCounter.Isolation.increment_count_preserves_owner
#print axioms Verity.Proofs.OwnedCounter.Isolation.decrement_count_preserves_owner
#print axioms Verity.Proofs.OwnedCounter.Isolation.constructor_owner_preserves_count
#print axioms Verity.Proofs.OwnedCounter.Isolation.transferOwnership_owner_preserves_count
#print axioms Verity.Proofs.OwnedCounter.Isolation.constructor_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.increment_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.decrement_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.transferOwnership_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.getCount_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.getOwner_context_preserved
#print axioms Verity.Proofs.OwnedCounter.Isolation.constructor_preserves_map_storage
#print axioms Verity.Proofs.OwnedCounter.Isolation.increment_preserves_map_storage
#print axioms Verity.Proofs.OwnedCounter.Isolation.decrement_preserves_map_storage
#print axioms Verity.Proofs.OwnedCounter.Isolation.transferOwnership_preserves_map_storage

-- Verity/Proofs/SafeCounter/Basic.lean
#print axioms Verity.Proofs.SafeCounter.getCount_meets_spec
#print axioms Verity.Proofs.SafeCounter.getCount_returns_count
#print axioms Verity.Proofs.SafeCounter.getCount_preserves_state
#print axioms Verity.Proofs.SafeCounter.evm_add_eq_of_no_overflow
-- #print axioms Verity.Proofs.SafeCounter.increment_unfold  -- private
#print axioms Verity.Proofs.SafeCounter.increment_meets_spec
#print axioms Verity.Proofs.SafeCounter.increment_adds_one
#print axioms Verity.Proofs.SafeCounter.increment_preserves_other_slots
#print axioms Verity.Proofs.SafeCounter.increment_reverts_overflow
-- #print axioms Verity.Proofs.SafeCounter.decrement_unfold  -- private
#print axioms Verity.Proofs.SafeCounter.decrement_meets_spec
#print axioms Verity.Proofs.SafeCounter.decrement_subtracts_one
#print axioms Verity.Proofs.SafeCounter.decrement_preserves_other_slots
#print axioms Verity.Proofs.SafeCounter.decrement_reverts_underflow
#print axioms Verity.Proofs.SafeCounter.increment_preserves_wellformedness
#print axioms Verity.Proofs.SafeCounter.decrement_preserves_wellformedness
#print axioms Verity.Proofs.SafeCounter.increment_preserves_bounds
#print axioms Verity.Proofs.SafeCounter.decrement_preserves_bounds
#print axioms Verity.Proofs.SafeCounter.increment_getCount_correct

-- Verity/Proofs/SafeCounter/Correctness.lean
#print axioms Verity.Proofs.SafeCounter.Correctness.increment_preserves_context
#print axioms Verity.Proofs.SafeCounter.Correctness.decrement_preserves_context
#print axioms Verity.Proofs.SafeCounter.Correctness.increment_preserves_storage_isolated
#print axioms Verity.Proofs.SafeCounter.Correctness.decrement_preserves_storage_isolated
#print axioms Verity.Proofs.SafeCounter.Correctness.getCount_preserves_context
#print axioms Verity.Proofs.SafeCounter.Correctness.getCount_preserves_wellformedness
#print axioms Verity.Proofs.SafeCounter.Correctness.increment_decrement_cancel
#print axioms Verity.Proofs.SafeCounter.Correctness.decrement_getCount_correct

-- Verity/Proofs/SimpleStorage/Basic.lean
#print axioms Verity.Proofs.SimpleStorage.setStorage_updates_slot
#print axioms Verity.Proofs.SimpleStorage.getStorage_reads_slot
#print axioms Verity.Proofs.SimpleStorage.setStorage_preserves_other_slots
#print axioms Verity.Proofs.SimpleStorage.setStorage_preserves_sender
#print axioms Verity.Proofs.SimpleStorage.setStorage_preserves_address
#print axioms Verity.Proofs.SimpleStorage.setStorage_preserves_addr_storage
#print axioms Verity.Proofs.SimpleStorage.setStorage_preserves_map_storage
#print axioms Verity.Proofs.SimpleStorage.store_meets_spec
#print axioms Verity.Proofs.SimpleStorage.retrieve_meets_spec
#print axioms Verity.Proofs.SimpleStorage.store_retrieve_correct
#print axioms Verity.Proofs.SimpleStorage.store_preserves_wellformedness
#print axioms Verity.Proofs.SimpleStorage.retrieve_preserves_state
#print axioms Verity.Proofs.SimpleStorage.retrieve_twice_idempotent

-- Verity/Proofs/SimpleStorage/Correctness.lean
#print axioms Verity.Proofs.SimpleStorage.Correctness.store_retrieve_roundtrip_holds
#print axioms Verity.Proofs.SimpleStorage.Correctness.store_preserves_storage_isolated
#print axioms Verity.Proofs.SimpleStorage.Correctness.store_preserves_addr_storage
#print axioms Verity.Proofs.SimpleStorage.Correctness.store_preserves_map_storage
#print axioms Verity.Proofs.SimpleStorage.Correctness.store_preserves_context
#print axioms Verity.Proofs.SimpleStorage.Correctness.retrieve_preserves_context
#print axioms Verity.Proofs.SimpleStorage.Correctness.retrieve_preserves_wellformedness

-- Verity/Proofs/SimpleToken/Basic.lean
#print axioms Verity.Proofs.SimpleToken.setStorageAddr_updates_owner
#print axioms Verity.Proofs.SimpleToken.setStorage_updates_supply
#print axioms Verity.Proofs.SimpleToken.setMapping_updates_balance
#print axioms Verity.Proofs.SimpleToken.getMapping_reads_balance
#print axioms Verity.Proofs.SimpleToken.getStorage_reads_supply
#print axioms Verity.Proofs.SimpleToken.getStorageAddr_reads_owner
#print axioms Verity.Proofs.SimpleToken.setMapping_preserves_other_addresses
#print axioms Verity.Proofs.SimpleToken.constructor_meets_spec
#print axioms Verity.Proofs.SimpleToken.constructor_sets_owner
#print axioms Verity.Proofs.SimpleToken.constructor_sets_supply_zero
#print axioms Verity.Proofs.SimpleToken.isOwner_true_when_owner
-- #print axioms Verity.Proofs.SimpleToken.mint_unfold  -- private
#print axioms Verity.Proofs.SimpleToken.mint_meets_spec_when_owner
#print axioms Verity.Proofs.SimpleToken.mint_increases_balance
#print axioms Verity.Proofs.SimpleToken.mint_increases_supply
#print axioms Verity.Proofs.SimpleToken.mint_reverts_balance_overflow
#print axioms Verity.Proofs.SimpleToken.mint_reverts_supply_overflow
-- #print axioms Verity.Proofs.SimpleToken.transfer_unfold_self  -- private
-- #print axioms Verity.Proofs.SimpleToken.transfer_unfold_other  -- private
#print axioms Verity.Proofs.SimpleToken.transfer_meets_spec_when_sufficient
#print axioms Verity.Proofs.SimpleToken.transfer_preserves_supply_when_sufficient
#print axioms Verity.Proofs.SimpleToken.transfer_decreases_sender_balance
#print axioms Verity.Proofs.SimpleToken.transfer_increases_recipient_balance
#print axioms Verity.Proofs.SimpleToken.transfer_self_preserves_balance
#print axioms Verity.Proofs.SimpleToken.transfer_reverts_recipient_overflow
#print axioms Verity.Proofs.SimpleToken.balanceOf_meets_spec
#print axioms Verity.Proofs.SimpleToken.balanceOf_returns_balance
#print axioms Verity.Proofs.SimpleToken.balanceOf_preserves_state
#print axioms Verity.Proofs.SimpleToken.getTotalSupply_meets_spec
#print axioms Verity.Proofs.SimpleToken.getTotalSupply_returns_supply
#print axioms Verity.Proofs.SimpleToken.getTotalSupply_preserves_state
#print axioms Verity.Proofs.SimpleToken.getOwner_meets_spec
#print axioms Verity.Proofs.SimpleToken.getOwner_returns_owner
#print axioms Verity.Proofs.SimpleToken.getOwner_preserves_state
#print axioms Verity.Proofs.SimpleToken.constructor_getTotalSupply_correct
#print axioms Verity.Proofs.SimpleToken.constructor_getOwner_correct
#print axioms Verity.Proofs.SimpleToken.constructor_preserves_wellformedness
#print axioms Verity.Proofs.SimpleToken.balanceOf_preserves_wellformedness
#print axioms Verity.Proofs.SimpleToken.getTotalSupply_preserves_wellformedness
#print axioms Verity.Proofs.SimpleToken.getOwner_preserves_wellformedness

-- Verity/Proofs/SimpleToken/Correctness.lean
#print axioms Verity.Proofs.SimpleToken.Correctness.mint_reverts_when_not_owner
#print axioms Verity.Proofs.SimpleToken.Correctness.transfer_reverts_insufficient_balance
#print axioms Verity.Proofs.SimpleToken.Correctness.mint_preserves_wellformedness
#print axioms Verity.Proofs.SimpleToken.Correctness.transfer_preserves_wellformedness
#print axioms Verity.Proofs.SimpleToken.Correctness.mint_preserves_owner
#print axioms Verity.Proofs.SimpleToken.Correctness.transfer_preserves_owner
#print axioms Verity.Proofs.SimpleToken.Correctness.mint_then_balanceOf_correct
#print axioms Verity.Proofs.SimpleToken.Correctness.mint_then_getTotalSupply_correct
#print axioms Verity.Proofs.SimpleToken.Correctness.transfer_then_balanceOf_sender_correct
#print axioms Verity.Proofs.SimpleToken.Correctness.transfer_then_balanceOf_recipient_correct

-- Verity/Proofs/SimpleToken/Isolation.lean
-- #print axioms Verity.Proofs.SimpleToken.Isolation.constructor_isolation  -- private
#print axioms Verity.Proofs.SimpleToken.Isolation.constructor_supply_storage_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.constructor_balance_mapping_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.constructor_owner_addr_isolated
-- #print axioms Verity.Proofs.SimpleToken.Isolation.mint_isolation  -- private
#print axioms Verity.Proofs.SimpleToken.Isolation.mint_supply_storage_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.mint_balance_mapping_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.mint_owner_addr_isolated
-- #print axioms Verity.Proofs.SimpleToken.Isolation.transfer_isolation  -- private
#print axioms Verity.Proofs.SimpleToken.Isolation.transfer_supply_storage_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.transfer_balance_mapping_isolated
#print axioms Verity.Proofs.SimpleToken.Isolation.transfer_owner_addr_isolated

-- Verity/Proofs/SimpleToken/Supply.lean
-- #print axioms Verity.Proofs.SimpleToken.Supply.map_sum_zero_of_all_zero  -- private
#print axioms Verity.Proofs.SimpleToken.Supply.constructor_establishes_supply_bounds
#print axioms Verity.Proofs.SimpleToken.Supply.mint_sum_equation
#print axioms Verity.Proofs.SimpleToken.Supply.mint_sum_singleton_to
#print axioms Verity.Proofs.SimpleToken.Supply.transfer_sum_equation
#print axioms Verity.Proofs.SimpleToken.Supply.transfer_sum_preserved_unique

-- Verity/Proofs/Stdlib/Automation.lean
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_owner_ownedCounter
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_owner_ownedCounter_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_count_ownedCounter
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_count_ownedCounter_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_count_safeCounter
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_count_safeCounter_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_balances_simpleToken
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_balances_simpleToken_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_owner_simpleToken
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_owner_simpleToken_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_totalSupply_simpleToken
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_totalSupply_simpleToken_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_balances_ledger
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_balances_ledger_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_newOwner
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_newOwner_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_initialOwner
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_initialOwner_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_to_to_amount
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_to_to_amount_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_amount_to_amount
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_amount_to_amount_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_addr
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_addr_decide
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_amount_single
#print axioms Verity.Proofs.Stdlib.Automation.findIdx_param_amount_single_decide
#print axioms Verity.Proofs.Stdlib.Automation.isSuccess_success
#print axioms Verity.Proofs.Stdlib.Automation.isSuccess_revert
#print axioms Verity.Proofs.Stdlib.Automation.getState_success
#print axioms Verity.Proofs.Stdlib.Automation.getState_revert
#print axioms Verity.Proofs.Stdlib.Automation.getStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.getStorage_runValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_getStorage
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_getStorage_diff
#print axioms Verity.Proofs.Stdlib.Automation.bind_pure_left
#print axioms Verity.Proofs.Stdlib.Automation.bind_pure_right
#print axioms Verity.Proofs.Stdlib.Automation.bind_assoc
#print axioms Verity.Proofs.Stdlib.Automation.bind_getStorage_setStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.bind_isSuccess_left
#print axioms Verity.Proofs.Stdlib.Automation.getStorageAddr_runState
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_runState
#print axioms Verity.Proofs.Stdlib.Automation.getStorageAddr_runValue
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_lt_modulus
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_mod_eq
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_beq_self
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_injective
#print axioms Verity.Proofs.Stdlib.Automation.getMapping_runState
#print axioms Verity.Proofs.Stdlib.Automation.getMapping_runValue
#print axioms Verity.Proofs.Stdlib.Automation.lookup_senderBal
#print axioms Verity.Proofs.Stdlib.Automation.lookup_recipientBal
#print axioms Verity.Proofs.Stdlib.Automation.lookup_senderBal_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_recipientBal_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_sameAddr_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_delta_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_amountDelta_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_addr_first
#print axioms Verity.Proofs.Stdlib.Automation.lookup_addr_second
#print axioms Verity.Proofs.Stdlib.Automation.lookup_slot_first
#print axioms Verity.Proofs.Stdlib.Automation.lookup_slot_second
#print axioms Verity.Proofs.Stdlib.Automation.msgSender_runState
#print axioms Verity.Proofs.Stdlib.Automation.msgSender_runValue
#print axioms Verity.Proofs.Stdlib.Automation.require_true_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.require_false_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.require_success_implies_cond
#print axioms Verity.Proofs.Stdlib.Automation.require_state
#print axioms Verity.Proofs.Stdlib.Automation.require_bind_true_run
#print axioms Verity.Proofs.Stdlib.Automation.require_bind_false_run
#print axioms Verity.Proofs.Stdlib.Automation.address_beq_eq_true_iff_eq
#print axioms Verity.Proofs.Stdlib.Automation.address_beq_false_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_ne_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_beq_false_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.one_mod_modulus
#print axioms Verity.Proofs.Stdlib.Automation.evm_add_eq_hadd
#print axioms Verity.Proofs.Stdlib.Automation.uint256_add_val
#print axioms Verity.Proofs.Stdlib.Automation.uint256_sub_val
#print axioms Verity.Proofs.Stdlib.Automation.uint256_sub_val_of_le
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_some_iff_ge
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_none_iff_lt
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_some_val
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_some_iff_le
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_none_iff_gt
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_some_val
#print axioms Verity.Proofs.Stdlib.Automation.add_one_preserves_order_iff_no_overflow
#print axioms Verity.Proofs.Stdlib.Automation.wf_of_state_eq
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_other_storage
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_storage
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_storage
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_runValue
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_runState
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_events_append
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_emitEvent_events
#print axioms Verity.Proofs.Stdlib.Automation.modulus_eq_max_uint256_succ
#print axioms Verity.Proofs.Stdlib.Automation.max_uint256_lt_modulus
#print axioms Verity.Proofs.Stdlib.Automation.lt_modulus_of_le_max_uint256
#print axioms Verity.Proofs.Stdlib.Automation.uint256_ge_val_le
#print axioms Verity.Proofs.Stdlib.Automation.amount_lt_modulus_of_val_ge
#print axioms Verity.Proofs.Stdlib.Automation.uint256_ofNat_le_of_val_ge
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_success_implies_eq
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_isSuccess_true_iff_eq
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_isSuccess_false_iff_ne
#print axioms Verity.Proofs.Stdlib.Automation.owner_guard_success_implies_storageAddr_eq_sender

-- Verity/Proofs/Stdlib/ListSum.lean
#print axioms Verity.Proofs.Stdlib.ListSum.countOcc_cons_eq
#print axioms Verity.Proofs.Stdlib.ListSum.countOcc_cons_ne
#print axioms Verity.Proofs.Stdlib.ListSum.countOccU_cons_eq
#print axioms Verity.Proofs.Stdlib.ListSum.countOccU_cons_ne
-- #print axioms Verity.Proofs.Stdlib.ListSum.mul_one_add  -- private
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_point_update
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_point_decrease
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_transfer_eq

-- Verity/Proofs/Stdlib/MappingAutomation.lean
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_getMapping_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_getMapping_diff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_other_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_same_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_other_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_mem_iff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMappingUint_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMappingUint_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_getMappingUint_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_getMappingUint_diff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storage
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_sender
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping2_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping2_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_diff_key1
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_diff_key2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storage
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_sender
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorage_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorage_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorageAddr_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorageAddr_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_events
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_events

-- Verity/Proofs/Stdlib/Math.lean
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_some
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_none
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_zero_left
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_zero_right
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_comm
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_result_bounded
#print axioms Verity.Proofs.Stdlib.Math.safeSub_some
#print axioms Verity.Proofs.Stdlib.Math.safeSub_none
#print axioms Verity.Proofs.Stdlib.Math.safeSub_zero
#print axioms Verity.Proofs.Stdlib.Math.safeSub_self
#print axioms Verity.Proofs.Stdlib.Math.safeSub_result_le
#print axioms Verity.Proofs.Stdlib.Math.safeMul_some
#print axioms Verity.Proofs.Stdlib.Math.safeMul_none
#print axioms Verity.Proofs.Stdlib.Math.safeMul_zero_left
#print axioms Verity.Proofs.Stdlib.Math.safeMul_zero_right
#print axioms Verity.Proofs.Stdlib.Math.safeMul_one_left
#print axioms Verity.Proofs.Stdlib.Math.safeMul_one_right
#print axioms Verity.Proofs.Stdlib.Math.safeMul_comm
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_some
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_none
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_zero_numerator
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_by_one
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_self
#print axioms Verity.Proofs.Stdlib.Math.safeMul_result_bounded
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_result_le_numerator

-- Compiler/Proofs/ArithmeticProfile.lean
#print axioms Compiler.Proofs.ArithmeticProfile.modulus_is_2_pow_256
#print axioms Compiler.Proofs.ArithmeticProfile.evmyullean_size_eq_verity_modulus
#print axioms Compiler.Proofs.ArithmeticProfile.add_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.sub_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.mul_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.div_by_zero
#print axioms Compiler.Proofs.ArithmeticProfile.mod_by_zero

-- Compiler/Proofs/EndToEnd.lean
#print axioms Compiler.Proofs.EndToEnd.layer3_function_preserves_semantics
#print axioms Compiler.Proofs.EndToEnd.interpretYulRuntime_eq_yulResultOfExec
#print axioms Compiler.Proofs.EndToEnd.yulStateOfIR_eq_initial
#print axioms Compiler.Proofs.EndToEnd.execYulStmts_paramState_eq_emptyVars
#print axioms Compiler.Proofs.EndToEnd.yulBody_from_state_eq_yulBody
#print axioms Compiler.Proofs.EndToEnd.layer3_contract_preserves_semantics
#print axioms Compiler.Proofs.EndToEnd.layer3_contract_preserves_semantics_general
#print axioms Compiler.Proofs.EndToEnd.layers2_3_ir_matches_yul
#print axioms Compiler.Proofs.EndToEnd.simpleStorage_endToEnd

-- Compiler/Proofs/IRGeneration/IRInterpreter.lean
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_stop_succ
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_sstore_lit_lit_succ
#print axioms Compiler.Proofs.IRGeneration.execIRStmts_single_stop_succ_succ

-- Compiler/Proofs/MappingSlot.lean
#print axioms Compiler.Proofs.abstractMappingSlot_eq_solidity
#print axioms Compiler.Proofs.abstractMappingTag_eq_zero
#print axioms Compiler.Proofs.abstractDecodeMappingSlot_eq_none
#print axioms Compiler.Proofs.activeMappingSlotBackend_eq_keccak
#print axioms Compiler.Proofs.activeMappingSlotBackendIsEvmFaithful_eq_true
#print axioms Compiler.Proofs.abstractNestedMappingSlot_eq_solidityNested
#print axioms Compiler.Proofs.abstractLoadMappingEntry_eq
#print axioms Compiler.Proofs.abstractStoreMappingEntry_eq
#print axioms Compiler.Proofs.abstractLoadStorageOrMapping_eq
#print axioms Compiler.Proofs.abstractStoreStorageOrMapping_eq

-- Compiler/Proofs/SemanticBridge.lean
#print axioms Compiler.Proofs.SemanticBridge.spec_to_ir_preserves_semantics
#print axioms Compiler.Proofs.SemanticBridge.simpleStorage_store_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.simpleStorage_retrieve_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.counter_increment_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.counter_decrement_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.counter_getCount_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.owned_getOwner_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.owned_transferOwnership_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.safeCounter_increment_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.safeCounter_decrement_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.safeCounter_getCount_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.ownedCounter_getCount_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.ownedCounter_getOwner_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.ownedCounter_increment_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.ownedCounter_decrement_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.ownedCounter_transferOwnership_semantic_bridge
#print axioms Compiler.Proofs.SemanticBridge.simpleStorage_store_edsl_to_yul
#print axioms Compiler.Proofs.SemanticBridge.simpleStorage_retrieve_edsl_to_yul
#print axioms Compiler.Proofs.SemanticBridge.counter_increment_edsl_to_yul

-- Compiler/Proofs/YulGeneration/Builtins.lean
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_callvalue_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_calldatasize_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_caller_nil
#print axioms Compiler.Proofs.YulGeneration.calldataloadWord_offset4
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_calldataload_offset4_single
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCallWithBackend_calldataload_offset4_single

-- Compiler/Proofs/YulGeneration/Equivalence.lean
#print axioms Compiler.Proofs.YulGeneration.resultsMatch_of_execResultsAligned
#print axioms Compiler.Proofs.YulGeneration.statesAligned_refl
#print axioms Compiler.Proofs.YulGeneration.execYulStmtsFuel_nil
#print axioms Compiler.Proofs.YulGeneration.execYulStmtsFuel_cons
#print axioms Compiler.Proofs.YulGeneration.execYulStmtFuel_for
-- #print axioms Compiler.Proofs.YulGeneration.stmt_align_contra  -- private
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_nil
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_cons
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_equiv_execYulStmtsFuel_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_equiv_execYulStmts_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRFunctionFuel_equiv_interpretYulBodyFromState_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_fuel_goal_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRFunctionFuel_adequate
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_fuel_goal
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_fuel_goal_and_adequacy
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_stmt_equiv_and_adequacy
-- Total: 560 theorems/lemmas (539 public, 21 private)
