-- Auto-generated by scripts/generate_print_axioms.py
-- Runs #print axioms on all top-level theorems/lemmas in proof directories.
-- Regenerate with: python3 scripts/generate_print_axioms.py

import Contracts.Counter.Proofs.Basic
import Contracts.Counter.Proofs.Correctness
import Contracts.ERC20.Proofs.Basic
import Contracts.ERC20.Proofs.Correctness
import Contracts.ERC721.Proofs.Basic
import Contracts.ERC721.Proofs.Correctness
import Contracts.Ledger.Proofs.Basic
import Contracts.Ledger.Proofs.Conservation
import Contracts.Ledger.Proofs.Correctness
import Contracts.LocalObligationMacroSmoke.Proofs.Basic
import Contracts.LocalObligationMacroSmoke.Proofs.Correctness
import Contracts.Owned.Proofs.Basic
import Contracts.Owned.Proofs.Correctness
import Contracts.OwnedCounter.Proofs.Basic
import Contracts.OwnedCounter.Proofs.Correctness
import Contracts.OwnedCounter.Proofs.Isolation
import Contracts.SafeCounter.Proofs.Basic
import Contracts.SafeCounter.Proofs.Correctness
import Contracts.SimpleStorage.Proofs.Basic
import Contracts.SimpleStorage.Proofs.Correctness
import Contracts.SimpleToken.Proofs.Basic
import Contracts.SimpleToken.Proofs.Correctness
import Contracts.SimpleToken.Proofs.Isolation
import Contracts.SimpleToken.Proofs.Supply
import Verity.Proofs.Stdlib.Automation
import Verity.Proofs.Stdlib.ListSum
import Verity.Proofs.Stdlib.MappingAutomation
import Verity.Proofs.Stdlib.Math
import Compiler.Proofs.ArithmeticProfile
import Compiler.Proofs.EndToEnd
import Compiler.Proofs.IRGeneration.IRInterpreter
import Compiler.Proofs.IRGeneration.SupportedFragment
import Compiler.Proofs.MappingSlot
import Compiler.Proofs.YulGeneration.Backends.EvmYulLeanBridgeLemmas
import Compiler.Proofs.YulGeneration.Builtins
import Compiler.Proofs.YulGeneration.Equivalence

-- Contracts/Counter/Proofs/Basic.lean
#print axioms Contracts.Counter.Proofs.setStorage_updates_count
#print axioms Contracts.Counter.Proofs.getStorage_reads_count
#print axioms Contracts.Counter.Proofs.setStorage_preserves_other_slots
#print axioms Contracts.Counter.Proofs.setStorage_preserves_context
#print axioms Contracts.Counter.Proofs.setStorage_preserves_addr_storage
#print axioms Contracts.Counter.Proofs.setStorage_preserves_map_storage
#print axioms Contracts.Counter.Proofs.increment_meets_spec
#print axioms Contracts.Counter.Proofs.increment_adds_one
#print axioms Contracts.Counter.Proofs.decrement_meets_spec
#print axioms Contracts.Counter.Proofs.decrement_subtracts_one
#print axioms Contracts.Counter.Proofs.getCount_meets_spec
#print axioms Contracts.Counter.Proofs.getCount_reads_count_value
#print axioms Contracts.Counter.Proofs.increment_getCount_correct
#print axioms Contracts.Counter.Proofs.decrement_getCount_correct
#print axioms Contracts.Counter.Proofs.increment_twice_adds_two
#print axioms Contracts.Counter.Proofs.increment_decrement_cancel
#print axioms Contracts.Counter.Proofs.increment_preserves_wellformedness
#print axioms Contracts.Counter.Proofs.decrement_preserves_wellformedness
#print axioms Contracts.Counter.Proofs.getCount_preserves_state

-- Contracts/Counter/Proofs/Correctness.lean
#print axioms Contracts.Counter.Proofs.Correctness.increment_state_preserved_except_count
#print axioms Contracts.Counter.Proofs.Correctness.decrement_state_preserved_except_count
#print axioms Contracts.Counter.Proofs.Correctness.getCount_state_preserved
#print axioms Contracts.Counter.Proofs.Correctness.increment_getCount_meets_spec
#print axioms Contracts.Counter.Proofs.Correctness.decrement_getCount_meets_spec
#print axioms Contracts.Counter.Proofs.Correctness.two_increments_meets_spec
#print axioms Contracts.Counter.Proofs.Correctness.increment_decrement_meets_cancel
#print axioms Contracts.Counter.Proofs.Correctness.getCount_preserves_wellformedness
#print axioms Contracts.Counter.Proofs.Correctness.decrement_at_zero_wraps_max

-- Contracts/ERC20/Proofs/Basic.lean
#print axioms Contracts.ERC20.Proofs.constructor_meets_spec
#print axioms Contracts.ERC20.Proofs.approve_meets_spec
#print axioms Contracts.ERC20.Proofs.balanceOf_meets_spec
#print axioms Contracts.ERC20.Proofs.allowanceOf_meets_spec
#print axioms Contracts.ERC20.Proofs.totalSupply_meets_spec
#print axioms Contracts.ERC20.Proofs.getOwner_meets_spec
-- #print axioms Contracts.ERC20.Proofs.mint_unfold  -- private
#print axioms Contracts.ERC20.Proofs.mint_meets_spec_when_owner
#print axioms Contracts.ERC20.Proofs.mint_increases_balance_when_owner
#print axioms Contracts.ERC20.Proofs.mint_increases_supply_when_owner
-- #print axioms Contracts.ERC20.Proofs.transfer_unfold_self  -- private
-- #print axioms Contracts.ERC20.Proofs.transfer_unfold_other  -- private
#print axioms Contracts.ERC20.Proofs.transfer_meets_spec_when_sufficient
#print axioms Contracts.ERC20.Proofs.transfer_decreases_sender_balance_when_sufficient
#print axioms Contracts.ERC20.Proofs.transfer_increases_recipient_balance_when_sufficient

-- Contracts/ERC20/Proofs/Correctness.lean
#print axioms Contracts.ERC20.Proofs.balanceOf_preserves_state
#print axioms Contracts.ERC20.Proofs.allowanceOf_preserves_state
#print axioms Contracts.ERC20.Proofs.getTotalSupply_preserves_state
#print axioms Contracts.ERC20.Proofs.getOwner_preserves_state
#print axioms Contracts.ERC20.Proofs.approve_is_balance_neutral_holds
#print axioms Contracts.ERC20.Proofs.transfer_preserves_totalSupply_when_sufficient
#print axioms Contracts.ERC20.Proofs.transfer_preserves_owner_when_sufficient

-- Contracts/ERC721/Proofs/Basic.lean
#print axioms Contracts.ERC721.Proofs.constructor_meets_spec
#print axioms Contracts.ERC721.Proofs.balanceOf_meets_spec
#print axioms Contracts.ERC721.Proofs.ownerOf_meets_spec
#print axioms Contracts.ERC721.Proofs.getApproved_meets_spec
#print axioms Contracts.ERC721.Proofs.isApprovedForAll_meets_spec
#print axioms Contracts.ERC721.Proofs.setApprovalForAll_meets_spec

-- Contracts/ERC721/Proofs/Correctness.lean
#print axioms Contracts.ERC721.Proofs.balanceOf_preserves_state
#print axioms Contracts.ERC721.Proofs.ownerOf_preserves_state
#print axioms Contracts.ERC721.Proofs.getApproved_preserves_state
#print axioms Contracts.ERC721.Proofs.isApprovedForAll_preserves_state
#print axioms Contracts.ERC721.Proofs.setApprovalForAll_is_balance_neutral_holds

-- Contracts/Ledger/Proofs/Basic.lean
#print axioms Contracts.Ledger.Proofs.getBalance_meets_spec
#print axioms Contracts.Ledger.Proofs.getBalance_returns_balance
#print axioms Contracts.Ledger.Proofs.getBalance_preserves_state
-- #print axioms Contracts.Ledger.Proofs.deposit_unfold  -- private
#print axioms Contracts.Ledger.Proofs.deposit_meets_spec
#print axioms Contracts.Ledger.Proofs.deposit_increases_balance
#print axioms Contracts.Ledger.Proofs.deposit_preserves_other_balances
-- #print axioms Contracts.Ledger.Proofs.withdraw_unfold  -- private
#print axioms Contracts.Ledger.Proofs.withdraw_meets_spec
#print axioms Contracts.Ledger.Proofs.withdraw_decreases_balance
#print axioms Contracts.Ledger.Proofs.withdraw_reverts_insufficient
-- #print axioms Contracts.Ledger.Proofs.transfer_unfold_self  -- private
-- #print axioms Contracts.Ledger.Proofs.transfer_unfold_other  -- private
#print axioms Contracts.Ledger.Proofs.transfer_meets_spec
#print axioms Contracts.Ledger.Proofs.transfer_self_preserves_balance
#print axioms Contracts.Ledger.Proofs.transfer_decreases_sender
#print axioms Contracts.Ledger.Proofs.transfer_increases_recipient
#print axioms Contracts.Ledger.Proofs.transfer_reverts_insufficient
#print axioms Contracts.Ledger.Proofs.transfer_succeeds_recipient_overflow
#print axioms Contracts.Ledger.Proofs.deposit_preserves_non_mapping
#print axioms Contracts.Ledger.Proofs.withdraw_preserves_non_mapping
#print axioms Contracts.Ledger.Proofs.deposit_preserves_wellformedness
#print axioms Contracts.Ledger.Proofs.withdraw_preserves_wellformedness
#print axioms Contracts.Ledger.Proofs.deposit_getBalance_correct

-- Contracts/Ledger/Proofs/Conservation.lean
#print axioms Contracts.Ledger.Proofs.Conservation.deposit_sum_equation
#print axioms Contracts.Ledger.Proofs.Conservation.deposit_sum_singleton_sender
#print axioms Contracts.Ledger.Proofs.Conservation.withdraw_sum_equation
#print axioms Contracts.Ledger.Proofs.Conservation.withdraw_sum_singleton_sender
#print axioms Contracts.Ledger.Proofs.Conservation.transfer_sum_equation
#print axioms Contracts.Ledger.Proofs.Conservation.transfer_sum_preserved_unique
#print axioms Contracts.Ledger.Proofs.Conservation.deposit_withdraw_sum_cancel

-- Contracts/Ledger/Proofs/Correctness.lean
#print axioms Contracts.Ledger.Proofs.Correctness.transfer_preserves_wellformedness
#print axioms Contracts.Ledger.Proofs.Correctness.transfer_preserves_non_mapping
#print axioms Contracts.Ledger.Proofs.Correctness.withdraw_getBalance_correct
#print axioms Contracts.Ledger.Proofs.Correctness.transfer_getBalance_sender_correct
#print axioms Contracts.Ledger.Proofs.Correctness.transfer_getBalance_recipient_correct
#print axioms Contracts.Ledger.Proofs.Correctness.deposit_withdraw_cancel

-- Contracts/LocalObligationMacroSmoke/Proofs/Basic.lean
#print axioms Contracts.LocalObligationMacroSmoke.Proofs.unsafeEdge_preserves_state
#print axioms Contracts.LocalObligationMacroSmoke.Proofs.dischargedEdge_meets_spec
#print axioms Contracts.LocalObligationMacroSmoke.Proofs.dischargedEdge_preserves_slot_zero

-- Contracts/LocalObligationMacroSmoke/Proofs/Correctness.lean
#print axioms Contracts.LocalObligationMacroSmoke.Proofs.Correctness.dischargedEdge_roundtrip

-- Contracts/Owned/Proofs/Basic.lean
#print axioms Contracts.Owned.Proofs.setStorageAddr_updates_owner
#print axioms Contracts.Owned.Proofs.getStorageAddr_reads_owner
#print axioms Contracts.Owned.Proofs.setStorageAddr_preserves_other_slots
#print axioms Contracts.Owned.Proofs.setStorageAddr_preserves_uint_storage
#print axioms Contracts.Owned.Proofs.setStorageAddr_preserves_map_storage
#print axioms Contracts.Owned.Proofs.setStorageAddr_preserves_context
#print axioms Contracts.Owned.Proofs.constructor_meets_spec
#print axioms Contracts.Owned.Proofs.constructor_sets_owner
#print axioms Contracts.Owned.Proofs.getOwner_meets_spec
#print axioms Contracts.Owned.Proofs.getOwner_returns_owner
#print axioms Contracts.Owned.Proofs.getOwner_preserves_state
#print axioms Contracts.Owned.Proofs.isOwner_meets_spec
#print axioms Contracts.Owned.Proofs.isOwner_returns_correct_value
#print axioms Contracts.Owned.Proofs.transferOwnership_unfold
#print axioms Contracts.Owned.Proofs.transferOwnership_meets_spec_when_owner
#print axioms Contracts.Owned.Proofs.transferOwnership_changes_owner_when_allowed
#print axioms Contracts.Owned.Proofs.constructor_getOwner_correct
#print axioms Contracts.Owned.Proofs.constructor_preserves_wellformedness
#print axioms Contracts.Owned.Proofs.getOwner_preserves_wellformedness

-- Contracts/Owned/Proofs/Correctness.lean
#print axioms Contracts.Owned.Proofs.Correctness.transferOwnership_reverts_when_not_owner
#print axioms Contracts.Owned.Proofs.Correctness.transferOwnership_preserves_wellformedness
#print axioms Contracts.Owned.Proofs.Correctness.constructor_transferOwnership_getOwner
#print axioms Contracts.Owned.Proofs.Correctness.transferred_owner_cannot_act

-- Contracts/OwnedCounter/Proofs/Basic.lean
-- #print axioms Contracts.OwnedCounter.Proofs.onlyOwner_reverts  -- private
-- #print axioms Contracts.OwnedCounter.Proofs.guarded_reverts  -- private
#print axioms Contracts.OwnedCounter.Proofs.constructor_meets_spec
#print axioms Contracts.OwnedCounter.Proofs.constructor_sets_owner
#print axioms Contracts.OwnedCounter.Proofs.constructor_preserves_count
-- #print axioms Contracts.OwnedCounter.Proofs.getCount_run  -- private
#print axioms Contracts.OwnedCounter.Proofs.getCount_meets_spec
#print axioms Contracts.OwnedCounter.Proofs.getCount_returns_count
#print axioms Contracts.OwnedCounter.Proofs.getCount_preserves_state
-- #print axioms Contracts.OwnedCounter.Proofs.getOwner_run  -- private
#print axioms Contracts.OwnedCounter.Proofs.getOwner_meets_spec
#print axioms Contracts.OwnedCounter.Proofs.getOwner_returns_owner
#print axioms Contracts.OwnedCounter.Proofs.getOwner_preserves_state
#print axioms Contracts.OwnedCounter.Proofs.isOwner_correct
#print axioms Contracts.OwnedCounter.Proofs.increment_unfold
#print axioms Contracts.OwnedCounter.Proofs.increment_meets_spec_when_owner
#print axioms Contracts.OwnedCounter.Proofs.increment_adds_one_when_owner
#print axioms Contracts.OwnedCounter.Proofs.increment_reverts_when_not_owner
#print axioms Contracts.OwnedCounter.Proofs.decrement_unfold
#print axioms Contracts.OwnedCounter.Proofs.decrement_meets_spec_when_owner
#print axioms Contracts.OwnedCounter.Proofs.decrement_subtracts_one_when_owner
#print axioms Contracts.OwnedCounter.Proofs.decrement_reverts_when_not_owner
#print axioms Contracts.OwnedCounter.Proofs.transferOwnership_unfold
#print axioms Contracts.OwnedCounter.Proofs.transferOwnership_meets_spec_when_owner
#print axioms Contracts.OwnedCounter.Proofs.transferOwnership_changes_owner
#print axioms Contracts.OwnedCounter.Proofs.transferOwnership_reverts_when_not_owner
#print axioms Contracts.OwnedCounter.Proofs.increment_preserves_owner
#print axioms Contracts.OwnedCounter.Proofs.decrement_preserves_owner
#print axioms Contracts.OwnedCounter.Proofs.transferOwnership_preserves_count
#print axioms Contracts.OwnedCounter.Proofs.constructor_preserves_wellformedness
#print axioms Contracts.OwnedCounter.Proofs.increment_preserves_wellformedness
#print axioms Contracts.OwnedCounter.Proofs.decrement_preserves_wellformedness
#print axioms Contracts.OwnedCounter.Proofs.constructor_increment_getCount

-- Contracts/OwnedCounter/Proofs/Correctness.lean
-- #print axioms Contracts.OwnedCounter.Proofs.Correctness.transfer_sender_not_new_owner  -- private
#print axioms Contracts.OwnedCounter.Proofs.Correctness.transfer_then_increment_reverts
#print axioms Contracts.OwnedCounter.Proofs.Correctness.transfer_then_decrement_reverts
#print axioms Contracts.OwnedCounter.Proofs.Correctness.transfer_then_transfer_reverts
#print axioms Contracts.OwnedCounter.Proofs.Correctness.transferOwnership_preserves_wellformedness
#print axioms Contracts.OwnedCounter.Proofs.Correctness.increment_survives_transfer

-- Contracts/OwnedCounter/Proofs/Isolation.lean
#print axioms Contracts.OwnedCounter.Proofs.Isolation.increment_count_preserves_owner
#print axioms Contracts.OwnedCounter.Proofs.Isolation.decrement_count_preserves_owner
#print axioms Contracts.OwnedCounter.Proofs.Isolation.constructor_owner_preserves_count
#print axioms Contracts.OwnedCounter.Proofs.Isolation.transferOwnership_owner_preserves_count
#print axioms Contracts.OwnedCounter.Proofs.Isolation.constructor_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.increment_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.decrement_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.transferOwnership_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.getCount_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.getOwner_context_preserved
#print axioms Contracts.OwnedCounter.Proofs.Isolation.constructor_preserves_map_storage
#print axioms Contracts.OwnedCounter.Proofs.Isolation.increment_preserves_map_storage
#print axioms Contracts.OwnedCounter.Proofs.Isolation.decrement_preserves_map_storage
#print axioms Contracts.OwnedCounter.Proofs.Isolation.transferOwnership_preserves_map_storage

-- Contracts/SafeCounter/Proofs/Basic.lean
-- #print axioms Contracts.SafeCounter.Proofs.getCount_run  -- private
#print axioms Contracts.SafeCounter.Proofs.getCount_meets_spec
#print axioms Contracts.SafeCounter.Proofs.getCount_returns_count
#print axioms Contracts.SafeCounter.Proofs.getCount_preserves_state
#print axioms Contracts.SafeCounter.Proofs.evm_add_eq_of_no_overflow
-- #print axioms Contracts.SafeCounter.Proofs.increment_unfold  -- private
#print axioms Contracts.SafeCounter.Proofs.increment_meets_spec
#print axioms Contracts.SafeCounter.Proofs.increment_adds_one
#print axioms Contracts.SafeCounter.Proofs.increment_preserves_other_slots
#print axioms Contracts.SafeCounter.Proofs.increment_reverts_overflow
-- #print axioms Contracts.SafeCounter.Proofs.decrement_unfold  -- private
#print axioms Contracts.SafeCounter.Proofs.decrement_meets_spec
#print axioms Contracts.SafeCounter.Proofs.decrement_subtracts_one
#print axioms Contracts.SafeCounter.Proofs.decrement_preserves_other_slots
#print axioms Contracts.SafeCounter.Proofs.decrement_reverts_underflow
#print axioms Contracts.SafeCounter.Proofs.increment_preserves_wellformedness
#print axioms Contracts.SafeCounter.Proofs.decrement_preserves_wellformedness
#print axioms Contracts.SafeCounter.Proofs.increment_preserves_bounds
#print axioms Contracts.SafeCounter.Proofs.decrement_preserves_bounds
#print axioms Contracts.SafeCounter.Proofs.increment_getCount_correct

-- Contracts/SafeCounter/Proofs/Correctness.lean
#print axioms Contracts.SafeCounter.Proofs.Correctness.increment_preserves_context
#print axioms Contracts.SafeCounter.Proofs.Correctness.decrement_preserves_context
#print axioms Contracts.SafeCounter.Proofs.Correctness.increment_preserves_storage_isolated
#print axioms Contracts.SafeCounter.Proofs.Correctness.decrement_preserves_storage_isolated
#print axioms Contracts.SafeCounter.Proofs.Correctness.getCount_preserves_context
#print axioms Contracts.SafeCounter.Proofs.Correctness.getCount_preserves_wellformedness
#print axioms Contracts.SafeCounter.Proofs.Correctness.increment_decrement_cancel
#print axioms Contracts.SafeCounter.Proofs.Correctness.decrement_getCount_correct

-- Contracts/SimpleStorage/Proofs/Basic.lean
#print axioms Contracts.SimpleStorage.Proofs.setStorage_updates_slot
#print axioms Contracts.SimpleStorage.Proofs.getStorage_reads_slot
#print axioms Contracts.SimpleStorage.Proofs.setStorage_preserves_other_slots
#print axioms Contracts.SimpleStorage.Proofs.setStorage_preserves_sender
#print axioms Contracts.SimpleStorage.Proofs.setStorage_preserves_address
#print axioms Contracts.SimpleStorage.Proofs.setStorage_preserves_addr_storage
#print axioms Contracts.SimpleStorage.Proofs.setStorage_preserves_map_storage
#print axioms Contracts.SimpleStorage.Proofs.store_meets_spec
#print axioms Contracts.SimpleStorage.Proofs.retrieve_meets_spec
#print axioms Contracts.SimpleStorage.Proofs.store_retrieve_correct
#print axioms Contracts.SimpleStorage.Proofs.store_preserves_wellformedness
#print axioms Contracts.SimpleStorage.Proofs.retrieve_preserves_state
#print axioms Contracts.SimpleStorage.Proofs.retrieve_twice_idempotent

-- Contracts/SimpleStorage/Proofs/Correctness.lean
#print axioms Contracts.SimpleStorage.Proofs.Correctness.store_retrieve_roundtrip_holds
#print axioms Contracts.SimpleStorage.Proofs.Correctness.store_preserves_storage_isolated
#print axioms Contracts.SimpleStorage.Proofs.Correctness.store_preserves_addr_storage
#print axioms Contracts.SimpleStorage.Proofs.Correctness.store_preserves_map_storage
#print axioms Contracts.SimpleStorage.Proofs.Correctness.store_preserves_context
#print axioms Contracts.SimpleStorage.Proofs.Correctness.retrieve_preserves_context
#print axioms Contracts.SimpleStorage.Proofs.Correctness.retrieve_preserves_wellformedness

-- Contracts/SimpleToken/Proofs/Basic.lean
#print axioms Contracts.SimpleToken.Proofs.setStorageAddr_updates_owner
#print axioms Contracts.SimpleToken.Proofs.setStorage_updates_supply
#print axioms Contracts.SimpleToken.Proofs.setMapping_updates_balance
#print axioms Contracts.SimpleToken.Proofs.getMapping_reads_balance
#print axioms Contracts.SimpleToken.Proofs.getStorage_reads_supply
#print axioms Contracts.SimpleToken.Proofs.getStorageAddr_reads_owner
#print axioms Contracts.SimpleToken.Proofs.setMapping_preserves_other_addresses
#print axioms Contracts.SimpleToken.Proofs.constructor_meets_spec
#print axioms Contracts.SimpleToken.Proofs.constructor_sets_owner
#print axioms Contracts.SimpleToken.Proofs.constructor_sets_supply_zero
#print axioms Contracts.SimpleToken.Proofs.isOwner_true_when_owner
-- #print axioms Contracts.SimpleToken.Proofs.mint_unfold  -- private
#print axioms Contracts.SimpleToken.Proofs.mint_meets_spec_when_owner
#print axioms Contracts.SimpleToken.Proofs.mint_increases_balance
#print axioms Contracts.SimpleToken.Proofs.mint_increases_supply
#print axioms Contracts.SimpleToken.Proofs.mint_reverts_balance_overflow
#print axioms Contracts.SimpleToken.Proofs.mint_reverts_supply_overflow
-- #print axioms Contracts.SimpleToken.Proofs.transfer_unfold_self  -- private
-- #print axioms Contracts.SimpleToken.Proofs.transfer_unfold_other  -- private
#print axioms Contracts.SimpleToken.Proofs.transfer_meets_spec_when_sufficient
#print axioms Contracts.SimpleToken.Proofs.transfer_preserves_supply_when_sufficient
#print axioms Contracts.SimpleToken.Proofs.transfer_decreases_sender_balance
#print axioms Contracts.SimpleToken.Proofs.transfer_increases_recipient_balance
#print axioms Contracts.SimpleToken.Proofs.transfer_self_preserves_balance
#print axioms Contracts.SimpleToken.Proofs.transfer_reverts_recipient_overflow
#print axioms Contracts.SimpleToken.Proofs.balanceOf_meets_spec
#print axioms Contracts.SimpleToken.Proofs.balanceOf_returns_balance
#print axioms Contracts.SimpleToken.Proofs.balanceOf_preserves_state
#print axioms Contracts.SimpleToken.Proofs.getTotalSupply_meets_spec
#print axioms Contracts.SimpleToken.Proofs.getTotalSupply_returns_supply
#print axioms Contracts.SimpleToken.Proofs.getTotalSupply_preserves_state
#print axioms Contracts.SimpleToken.Proofs.getOwner_meets_spec
#print axioms Contracts.SimpleToken.Proofs.getOwner_returns_owner
#print axioms Contracts.SimpleToken.Proofs.getOwner_preserves_state
#print axioms Contracts.SimpleToken.Proofs.constructor_getTotalSupply_correct
#print axioms Contracts.SimpleToken.Proofs.constructor_getOwner_correct
#print axioms Contracts.SimpleToken.Proofs.constructor_preserves_wellformedness
#print axioms Contracts.SimpleToken.Proofs.balanceOf_preserves_wellformedness
#print axioms Contracts.SimpleToken.Proofs.getTotalSupply_preserves_wellformedness
#print axioms Contracts.SimpleToken.Proofs.getOwner_preserves_wellformedness

-- Contracts/SimpleToken/Proofs/Correctness.lean
#print axioms Contracts.SimpleToken.Proofs.Correctness.mint_reverts_when_not_owner
#print axioms Contracts.SimpleToken.Proofs.Correctness.transfer_reverts_insufficient_balance
#print axioms Contracts.SimpleToken.Proofs.Correctness.mint_preserves_wellformedness
#print axioms Contracts.SimpleToken.Proofs.Correctness.transfer_preserves_wellformedness
#print axioms Contracts.SimpleToken.Proofs.Correctness.mint_preserves_owner
#print axioms Contracts.SimpleToken.Proofs.Correctness.transfer_preserves_owner
#print axioms Contracts.SimpleToken.Proofs.Correctness.mint_then_balanceOf_correct
#print axioms Contracts.SimpleToken.Proofs.Correctness.mint_then_getTotalSupply_correct
#print axioms Contracts.SimpleToken.Proofs.Correctness.transfer_then_balanceOf_sender_correct
#print axioms Contracts.SimpleToken.Proofs.Correctness.transfer_then_balanceOf_recipient_correct

-- Contracts/SimpleToken/Proofs/Isolation.lean
-- #print axioms Contracts.SimpleToken.Proofs.Isolation.constructor_isolation  -- private
#print axioms Contracts.SimpleToken.Proofs.Isolation.constructor_supply_storage_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.constructor_balance_mapping_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.constructor_owner_addr_isolated
-- #print axioms Contracts.SimpleToken.Proofs.Isolation.mint_isolation  -- private
#print axioms Contracts.SimpleToken.Proofs.Isolation.mint_supply_storage_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.mint_balance_mapping_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.mint_owner_addr_isolated
-- #print axioms Contracts.SimpleToken.Proofs.Isolation.transfer_isolation  -- private
#print axioms Contracts.SimpleToken.Proofs.Isolation.transfer_supply_storage_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.transfer_balance_mapping_isolated
#print axioms Contracts.SimpleToken.Proofs.Isolation.transfer_owner_addr_isolated

-- Contracts/SimpleToken/Proofs/Supply.lean
-- #print axioms Contracts.SimpleToken.Proofs.Supply.map_sum_zero_of_all_zero  -- private
#print axioms Contracts.SimpleToken.Proofs.Supply.constructor_establishes_supply_bounds
#print axioms Contracts.SimpleToken.Proofs.Supply.mint_sum_equation
#print axioms Contracts.SimpleToken.Proofs.Supply.mint_sum_singleton_to
#print axioms Contracts.SimpleToken.Proofs.Supply.transfer_sum_equation
#print axioms Contracts.SimpleToken.Proofs.Supply.transfer_sum_preserved_unique

-- Verity/Proofs/Stdlib/Automation.lean
#print axioms Verity.Proofs.Stdlib.Automation.isSuccess_success
#print axioms Verity.Proofs.Stdlib.Automation.isSuccess_revert
#print axioms Verity.Proofs.Stdlib.Automation.getState_success
#print axioms Verity.Proofs.Stdlib.Automation.getState_revert
#print axioms Verity.Proofs.Stdlib.Automation.getStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.getStorage_runValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_getStorage
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_getStorage_diff
#print axioms Verity.Proofs.Stdlib.Automation.bind_pure_left
#print axioms Verity.Proofs.Stdlib.Automation.bind_pure_right
#print axioms Verity.Proofs.Stdlib.Automation.bind_assoc
#print axioms Verity.Proofs.Stdlib.Automation.bind_getStorage_setStorage_runState
#print axioms Verity.Proofs.Stdlib.Automation.bind_isSuccess_left
#print axioms Verity.Proofs.Stdlib.Automation.getStorageAddr_runState
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_runState
#print axioms Verity.Proofs.Stdlib.Automation.getStorageAddr_runValue
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_lt_modulus
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_mod_eq
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_beq_self
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_injective
#print axioms Verity.Proofs.Stdlib.Automation.getMapping_runState
#print axioms Verity.Proofs.Stdlib.Automation.getMapping_runValue
#print axioms Verity.Proofs.Stdlib.Automation.lookup_senderBal
#print axioms Verity.Proofs.Stdlib.Automation.lookup_recipientBal
#print axioms Verity.Proofs.Stdlib.Automation.lookup_senderBal_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_recipientBal_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_sameAddr_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_delta_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_amountDelta_with_delta
#print axioms Verity.Proofs.Stdlib.Automation.lookup_addr_first
#print axioms Verity.Proofs.Stdlib.Automation.lookup_addr_second
#print axioms Verity.Proofs.Stdlib.Automation.lookup_slot_first
#print axioms Verity.Proofs.Stdlib.Automation.lookup_slot_second
#print axioms Verity.Proofs.Stdlib.Automation.msgSender_runState
#print axioms Verity.Proofs.Stdlib.Automation.msgSender_runValue
#print axioms Verity.Proofs.Stdlib.Automation.require_true_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.require_false_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.require_success_implies_cond
#print axioms Verity.Proofs.Stdlib.Automation.require_state
#print axioms Verity.Proofs.Stdlib.Automation.require_bind_true_run
#print axioms Verity.Proofs.Stdlib.Automation.require_bind_false_run
#print axioms Verity.Proofs.Stdlib.Automation.address_beq_eq_true_iff_eq
#print axioms Verity.Proofs.Stdlib.Automation.address_beq_false_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_ne_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.addressToNat_beq_false_of_ne
#print axioms Verity.Proofs.Stdlib.Automation.one_mod_modulus
#print axioms Verity.Proofs.Stdlib.Automation.evm_add_eq_hadd
#print axioms Verity.Proofs.Stdlib.Automation.uint256_add_val
#print axioms Verity.Proofs.Stdlib.Automation.uint256_sub_val
#print axioms Verity.Proofs.Stdlib.Automation.uint256_sub_val_of_le
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_some_iff_ge
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_none_iff_lt
#print axioms Verity.Proofs.Stdlib.Automation.safeSub_some_val
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_some_iff_le
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_none_iff_gt
#print axioms Verity.Proofs.Stdlib.Automation.safeAdd_some_val
#print axioms Verity.Proofs.Stdlib.Automation.safeMul_some_iff_le
#print axioms Verity.Proofs.Stdlib.Automation.safeMul_none_iff_gt
#print axioms Verity.Proofs.Stdlib.Automation.add_one_preserves_order_iff_no_overflow
#print axioms Verity.Proofs.Stdlib.Automation.wf_of_state_eq
#print axioms Verity.Proofs.Stdlib.Automation.wf_preservation_of_frame
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_other_storage
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_storage
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_storage
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_sender
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_blockNumber
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_blockNumber
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_blockNumber
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.Automation.setStorage_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.setStorageAddr_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.setMapping_preserves_events
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_isSuccess
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_runValue
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_runState
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_events_append
#print axioms Verity.Proofs.Stdlib.Automation.emitEvent_emitEvent_events
#print axioms Verity.Proofs.Stdlib.Automation.modulus_eq_max_uint256_succ
#print axioms Verity.Proofs.Stdlib.Automation.max_uint256_lt_modulus
#print axioms Verity.Proofs.Stdlib.Automation.lt_modulus_of_le_max_uint256
#print axioms Verity.Proofs.Stdlib.Automation.uint256_ge_val_le
#print axioms Verity.Proofs.Stdlib.Automation.amount_lt_modulus_of_val_ge
#print axioms Verity.Proofs.Stdlib.Automation.uint256_ofNat_le_of_val_ge
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_success_implies_eq
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_isSuccess_true_iff_eq
#print axioms Verity.Proofs.Stdlib.Automation.require_beq_isSuccess_false_iff_ne
#print axioms Verity.Proofs.Stdlib.Automation.owner_guard_success_implies_storageAddr_eq_sender

-- Verity/Proofs/Stdlib/ListSum.lean
#print axioms Verity.Proofs.Stdlib.ListSum.countOcc_cons_eq
#print axioms Verity.Proofs.Stdlib.ListSum.countOcc_cons_ne
#print axioms Verity.Proofs.Stdlib.ListSum.countOccU_cons_eq
#print axioms Verity.Proofs.Stdlib.ListSum.countOccU_cons_ne
-- #print axioms Verity.Proofs.Stdlib.ListSum.mul_one_add  -- private
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_point_update
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_point_decrease
#print axioms Verity.Proofs.Stdlib.ListSum.map_sum_transfer_eq

-- Verity/Proofs/Stdlib/MappingAutomation.lean
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_getMapping_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_getMapping_diff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_other_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_same_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_other_slot
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_knownAddresses_mem_iff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMappingUint_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMappingUint_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_getMappingUint_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_getMappingUint_diff
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storage
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_sender
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping2_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.getMapping2_runValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_runState
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_same
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_diff_key1
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_getMapping2_diff_key2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storage
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageAddr
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageMap
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_sender
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_thisAddress
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_knownAddresses
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_msgValue
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_blockTimestamp
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_blockNumber
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_blockNumber
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorage_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorage_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorageAddr_preserves_storageMapUint
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setStorageAddr_preserves_storageMap2
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMappingUint_preserves_events
#print axioms Verity.Proofs.Stdlib.MappingAutomation.setMapping2_preserves_events

-- Verity/Proofs/Stdlib/Math.lean
-- #print axioms Verity.Proofs.Stdlib.Math.modulus_eq_max_succ  -- private
-- #print axioms Verity.Proofs.Stdlib.Math.lt_modulus_of_le_max  -- private
#print axioms Verity.Proofs.Stdlib.Math.mulDivDown_nat_eq
#print axioms Verity.Proofs.Stdlib.Math.mulDivDown_mul_le
#print axioms Verity.Proofs.Stdlib.Math.mulDivDown_monotone_left
#print axioms Verity.Proofs.Stdlib.Math.mulDivDown_monotone_right
#print axioms Verity.Proofs.Stdlib.Math.mulDivUp_nat_eq
#print axioms Verity.Proofs.Stdlib.Math.mulDivDown_le_mulDivUp
#print axioms Verity.Proofs.Stdlib.Math.mulDivUp_monotone_left
#print axioms Verity.Proofs.Stdlib.Math.mulDivUp_monotone_right
#print axioms Verity.Proofs.Stdlib.Math.mulDivUp_mul_lt_add
#print axioms Verity.Proofs.Stdlib.Math.wMulDown_nat_eq
#print axioms Verity.Proofs.Stdlib.Math.wMulDown_mul_le
#print axioms Verity.Proofs.Stdlib.Math.wMulDown_monotone_left
#print axioms Verity.Proofs.Stdlib.Math.wMulDown_monotone_right
#print axioms Verity.Proofs.Stdlib.Math.wDivUp_nat_eq
#print axioms Verity.Proofs.Stdlib.Math.wDivUp_monotone_left
#print axioms Verity.Proofs.Stdlib.Math.wDivUp_mul_lt_add
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_some
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_none
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_zero_left
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_zero_right
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_comm
#print axioms Verity.Proofs.Stdlib.Math.safeAdd_result_bounded
#print axioms Verity.Proofs.Stdlib.Math.safeSub_some
#print axioms Verity.Proofs.Stdlib.Math.safeSub_none
#print axioms Verity.Proofs.Stdlib.Math.safeSub_zero
#print axioms Verity.Proofs.Stdlib.Math.safeSub_self
#print axioms Verity.Proofs.Stdlib.Math.safeSub_result_le
#print axioms Verity.Proofs.Stdlib.Math.safeMul_some
#print axioms Verity.Proofs.Stdlib.Math.safeMul_none
#print axioms Verity.Proofs.Stdlib.Math.safeMul_zero_left
#print axioms Verity.Proofs.Stdlib.Math.safeMul_zero_right
#print axioms Verity.Proofs.Stdlib.Math.safeMul_one_left
#print axioms Verity.Proofs.Stdlib.Math.safeMul_one_right
#print axioms Verity.Proofs.Stdlib.Math.safeMul_comm
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_some
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_none
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_zero_numerator
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_by_one
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_self
#print axioms Verity.Proofs.Stdlib.Math.safeMul_result_bounded
#print axioms Verity.Proofs.Stdlib.Math.safeDiv_result_le_numerator

-- Compiler/Proofs/ArithmeticProfile.lean
#print axioms Compiler.Proofs.ArithmeticProfile.modulus_is_2_pow_256
#print axioms Compiler.Proofs.ArithmeticProfile.evmyullean_size_eq_verity_modulus
#print axioms Compiler.Proofs.ArithmeticProfile.add_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.sub_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.mul_wraps
#print axioms Compiler.Proofs.ArithmeticProfile.div_by_zero
#print axioms Compiler.Proofs.ArithmeticProfile.mod_by_zero
#print axioms Compiler.Proofs.ArithmeticProfile.add_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.sub_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.mul_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.div_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.mod_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.and_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.or_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.xor_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.shl_bridge
#print axioms Compiler.Proofs.ArithmeticProfile.shr_bridge

-- Compiler/Proofs/EndToEnd.lean
#print axioms Compiler.Proofs.EndToEnd.layer3_function_preserves_semantics
#print axioms Compiler.Proofs.EndToEnd.interpretYulRuntime_eq_yulResultOfExec
#print axioms Compiler.Proofs.EndToEnd.yulStateOfIR_eq_initial
#print axioms Compiler.Proofs.EndToEnd.execYulStmts_paramState_eq_emptyVars
#print axioms Compiler.Proofs.EndToEnd.yulBody_from_state_eq_yulBody
#print axioms Compiler.Proofs.EndToEnd.layer3_contract_preserves_semantics
#print axioms Compiler.Proofs.EndToEnd.layer3_contract_preserves_semantics_general
#print axioms Compiler.Proofs.EndToEnd.layers2_3_ir_matches_yul
#print axioms Compiler.Proofs.EndToEnd.simpleStorage_endToEnd

-- Compiler/Proofs/IRGeneration/IRInterpreter.lean
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_stop_succ
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_stop_one_add
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_stop_one_add_add
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_sstore_lit_lit_succ
#print axioms Compiler.Proofs.IRGeneration.execIRStmt_sstore_lit_expr_succ_of_eval
#print axioms Compiler.Proofs.IRGeneration.execIRStmts_sstore_lit_expr_then_stop_succ_succ_succ_of_eval
#print axioms Compiler.Proofs.IRGeneration.execIRStmts_single_stop_succ_succ

-- Compiler/Proofs/IRGeneration/SupportedFragment.lean
#print axioms Compiler.Proofs.IRGeneration.supported_stmt_list_preserves_semantics

-- Compiler/Proofs/MappingSlot.lean
#print axioms Compiler.Proofs.abstractMappingSlot_eq_solidity
#print axioms Compiler.Proofs.abstractMappingTag_eq_zero
#print axioms Compiler.Proofs.abstractDecodeMappingSlot_eq_none
#print axioms Compiler.Proofs.activeMappingSlotBackend_eq_keccak
#print axioms Compiler.Proofs.activeMappingSlotBackendIsEvmFaithful_eq_true
#print axioms Compiler.Proofs.abstractNestedMappingSlot_eq_solidityNested
#print axioms Compiler.Proofs.abstractLoadMappingEntry_eq
#print axioms Compiler.Proofs.abstractStoreMappingEntry_eq
#print axioms Compiler.Proofs.abstractLoadStorageOrMapping_eq
#print axioms Compiler.Proofs.abstractStoreStorageOrMapping_eq

-- Compiler/Proofs/YulGeneration/Backends/EvmYulLeanBridgeLemmas.lean
-- #print axioms Compiler.Proofs.YulGeneration.Backends.word_lt_uint256_size  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_add_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_add_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_sub_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_sub_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_mul_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_mul_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_div_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_div_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_mod_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_mod_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_eq_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_eq_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_iszero_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_iszero_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_lt_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_lt_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.verity_eval_gt_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_gt_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_and_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_or_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_xor_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.xor_all_ones_uint256_word  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_not_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_shl_normalized  -- private
-- #print axioms Compiler.Proofs.YulGeneration.Backends.bridge_eval_shr_normalized  -- private
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_add_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_sub_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_mul_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_div_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_mod_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_eq_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_iszero_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_lt_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_gt_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_and_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_or_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_xor_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_not_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_shl_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCall_shr_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_add_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_sub_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_mul_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_div_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_mod_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_eq_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_iszero_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_lt_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_gt_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_and_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_or_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_xor_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_not_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_shl_bridge
#print axioms Compiler.Proofs.YulGeneration.Backends.evalBuiltinCallWithBackend_evmYulLean_shr_bridge

-- Compiler/Proofs/YulGeneration/Builtins.lean
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_callvalue_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_callvalue_context
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_calldatasize_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_caller_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_address_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_timestamp_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_number_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_chainid_nil
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_blobbasefee_nil
#print axioms Compiler.Proofs.YulGeneration.calldataloadWord_offset4
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_calldataload_offset4_single
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCallWithBackend_calldataload_offset4_single
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCall_sload_single
#print axioms Compiler.Proofs.YulGeneration.evalBuiltinCallWithBackend_sload_single

-- Compiler/Proofs/YulGeneration/Equivalence.lean
#print axioms Compiler.Proofs.YulGeneration.resultsMatch_of_execResultsAligned
#print axioms Compiler.Proofs.YulGeneration.statesAligned_refl
#print axioms Compiler.Proofs.YulGeneration.execYulStmtsFuel_nil
#print axioms Compiler.Proofs.YulGeneration.execYulStmtsFuel_cons
#print axioms Compiler.Proofs.YulGeneration.execYulStmtFuel_for
-- #print axioms Compiler.Proofs.YulGeneration.stmt_align_contra  -- private
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_nil
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_cons
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_equiv_execYulStmtsFuel_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRStmtsFuel_equiv_execYulStmts_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRFunctionFuel_equiv_interpretYulBodyFromState_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_fuel_goal_of_stmt_equiv
#print axioms Compiler.Proofs.YulGeneration.execIRFunctionFuel_adequate
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_fuel_goal
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_fuel_goal_and_adequacy
#print axioms Compiler.Proofs.YulGeneration.ir_yul_function_equiv_from_state_of_stmt_equiv_and_adequacy
-- Total: 621 theorems/lemmas (569 public, 52 private)
