name: Setup Foundry test environment
description: Download build artifacts, install Foundry and solc

runs:
  using: composite
  steps:
    - name: Download generated Yul
      uses: actions/download-artifact@v4
      with:
        name: generated-yul
        path: compiler/yul

    - name: Download difftest interpreter
      uses: actions/download-artifact@v4
      with:
        name: difftest-interpreter
        path: .lake/build/bin

    - name: Make difftest interpreter executable
      shell: bash
      run: chmod +x .lake/build/bin/difftest-interpreter

    - name: Install Foundry
      id: install_foundry_primary
      continue-on-error: true
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.5.0

    - name: Install Foundry fallback (retry on transient download errors)
      if: steps.install_foundry_primary.outcome != 'success'
      shell: bash
      run: |
        set -euo pipefail

        curl -fsSL https://foundry.paradigm.xyz | bash
        FOUNDRY_BIN="$HOME/.foundry/bin"
        export PATH="${FOUNDRY_BIN}:$PATH"
        echo "${FOUNDRY_BIN}" >> "$GITHUB_PATH"

        max_attempts=3
        attempt=1
        until "${FOUNDRY_BIN}/foundryup" --install 1.5.0; do
          if [ "$attempt" -ge "$max_attempts" ]; then
            echo "foundryup failed after ${max_attempts} attempts"
            exit 1
          fi
          sleep_seconds=$((attempt * 5))
          echo "foundryup attempt ${attempt} failed, retrying in ${sleep_seconds}s"
          sleep "$sleep_seconds"
          attempt=$((attempt + 1))
        done

    - name: Verify Foundry tools
      shell: bash
      run: |
        set -euo pipefail
        export PATH="$HOME/.foundry/bin:$PATH"
        forge --version
        cast --version
        anvil --version

    - name: Setup solc
      uses: ./.github/actions/setup-solc
