name: Setup Foundry test environment
description: Download build artifacts, install Foundry and solc

runs:
  using: composite
  steps:
    - name: Download generated Yul
      uses: actions/download-artifact@v4
      with:
        name: generated-yul
        path: compiler/yul

    - name: Download difftest interpreter
      uses: actions/download-artifact@v4
      with:
        name: difftest-interpreter
        path: .lake/build/bin

    - name: Make difftest interpreter executable
      shell: bash
      run: chmod +x .lake/build/bin/difftest-interpreter

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: v1.5.0

    - name: Setup solc
      uses: ./.github/actions/setup-solc
