import Lean
import Verity.Macro.Translate

namespace Verity.Macro

open Lean
open Lean.Elab
open Lean.Elab.Command

set_option hygiene false

/-- Bridge theorem generated by construction: the generated function-model body
    and named body definition are definitionally equal. -/
def mkBridgeCommand (fnIdent : Ident) : CommandElabM Cmd := do
  let modelBodyName ← mkSuffixedIdent fnIdent "_modelBody"
  let modelName ← mkSuffixedIdent fnIdent "_model"
  let bridgeName ← mkSuffixedIdent fnIdent "_bridge"
  `(command| theorem $bridgeName :
      (Compiler.CompilationModel.FunctionSpec.body ($modelName : Compiler.CompilationModel.FunctionSpec)) =
      $modelBodyName := rfl)

/-- Semantic preservation theorem per function (Issue #998, Phase 3).
    Re-exports the generated bridge fact under the historical
    `_semantic_preservation` name to avoid skeleton/placeholder theorems. -/
def mkSemanticBridgeCommand
    (contractIdent : Ident) (fields : Array StorageFieldDecl) (fnDecl : FunctionDecl)
    : CommandElabM Cmd := do
  let _ := contractIdent
  let _ := fields
  let semanticName ← mkSuffixedIdent fnDecl.ident "_semantic_preservation"
  let modelBodyName ← mkSuffixedIdent fnDecl.ident "_modelBody"
  let modelName ← mkSuffixedIdent fnDecl.ident "_model"
  let bridgeName ← mkSuffixedIdent fnDecl.ident "_bridge"

  `(command|
    /-- Auto-generated bridge fact under the historical semantic-preservation
        theorem name. This theorem is no longer a skeleton placeholder. -/
    theorem $semanticName :
        (Compiler.CompilationModel.FunctionSpec.body
          ($modelName : Compiler.CompilationModel.FunctionSpec)) =
        $modelBodyName := by
      simpa using $bridgeName)

/-- Auto-generated `_is_view` theorem for view functions (#1729, Axis 3 Step 1a).
    Emits a `@[simp]` lemma stating the model's `isView` flag is `true`, making this
    fact available to downstream proof automation.  Only called when `fnDecl.isView`. -/
def mkViewTheoremCommand (fnDecl : FunctionDecl) : CommandElabM Cmd := do
  let viewName ← mkSuffixedIdent fnDecl.ident "_is_view"
  let modelName ← mkSuffixedIdent fnDecl.ident "_model"
  `(command|
    /-- Auto-generated: this function is declared `view` and its model
        records that intent.  The corresponding `stmtWritesState` validation
        guarantees the body contains no state-writing statements. -/
    @[simp] theorem $viewName :
        (Compiler.CompilationModel.FunctionSpec.isView
          ($modelName : Compiler.CompilationModel.FunctionSpec)) = true := rfl)

end Verity.Macro
