// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by research/poc_constraints/dsl_to_constraints.py from specs/broken_capped_token.dc

import {BrokenCappedToken} from "./BrokenCappedToken.sol";

contract BrokenCappedTokenSpecHarness is BrokenCappedToken {
    constructor(address owner, uint256 supply, uint256 maxSupply) BrokenCappedToken(owner, supply, maxSupply) {}

    function mint_spec(uint256 amount) external {
         uint256 old_totalSupply = totalSupply;
        uint256 old_balance_owner = balance[owner];
        require(msg.sender == owner);
        require(totalSupply + amount <= maxSupply);

        super.mint(amount);
         assert(totalSupply == old_totalSupply + amount);
        assert(balance[owner] == old_balance_owner + amount);
        // invariant CapNotExceeded
        assert(totalSupply <= maxSupply);

    }
}
