// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by research/poc_constraints/dsl_to_constraints.py from specs/loan.dc

import {Loan} from "./Loan.sol";

contract LoanSpecHarness is Loan {
    constructor(uint256 minHealthFactor_) Loan(minHealthFactor_) {}

    function update_spec(address user, uint256 newCollateral, uint256 newDebt) external {
 
        super.update(user, newCollateral, newDebt);
         assert(debt[user] == 0 || collateral[user] * 1e18 >= debt[user] * minHealthFactor);
        // invariant MinHealthFactorPositive
        assert(minHealthFactor > 0);

    }
}
