// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by research/poc_constraints/dsl_to_constraints.py from specs/simple_token_witness.dc

import {SimpleTokenWitness} from "./SimpleTokenWitness.sol";

contract SimpleTokenWitnessSpecHarness is SimpleTokenWitness {
    constructor(address owner, uint256 supply) SimpleTokenWitness(owner, supply) {}

    function transferWitness_spec(address to, uint256 amount, address other) external {
         uint256 old_balance_msg_sender = balance[msg.sender];
        uint256 old_balance_to = balance[to];
        uint256 old_totalSupply = totalSupply;
        uint256 old_balance_other = balance[other];
        require(to != address(0));
        require(balance[msg.sender] >= amount);
        require(other != msg.sender && other != to);
        // hint: treat `other` as a witness for the "all other accounts unchanged" obligation
        // hint: forall witness other: other != msg.sender && other != to => balance[other] == old(balance[other])

        super.transferWitness(to, amount, other);
         assert(balance[msg.sender] == old_balance_msg_sender - amount);
        assert(balance[to] == old_balance_to + amount);
        assert(totalSupply == old_totalSupply);
        assert(balance[other] == old_balance_other);

    }
}
