// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by research/poc_constraints/dsl_to_constraints.py from specs/simple_token.dc

import {SimpleToken} from "./SimpleToken.sol";

contract SimpleTokenSpecHarness is SimpleToken {
    constructor(address owner, uint256 supply) SimpleToken(owner, supply) {}

    function transfer_spec(address to, uint256 amount) external {
        uint256 old_balance_msg_sender = balance[msg.sender];
        uint256 old_balance_to = balance[to];
        uint256 old_totalSupply = totalSupply;
        require(to != address(0));
        require(balance[msg.sender] >= amount);

        super.transfer(to, amount);
        assert(balance[msg.sender] == old_balance_msg_sender - amount);
        assert(balance[to] == old_balance_to + amount);
        assert(totalSupply == old_totalSupply);

    }
}
