namespace DumbContracts.EvmAsm

-- Minimal EVM asm emitter (same calling convention as Yul).

def directProgramAsm : List String :=
  [ "entry:"
  , "PUSH0"
  , "CALLDATALOAD"
  , "PUSH1 0xe0"
  , "SHR"
  , "DUP1"
  , "PUSH4 0x7eba7ba6"
  , "EQ"
  , "PUSH2 tag_getSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xf2c298be"
  , "EQ"
  , "PUSH2 tag_setSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x02222aec"
  , "EQ"
  , "PUSH2 tag_addSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x49f583e3"
  , "EQ"
  , "PUSH2 tag_guardedAddSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xb61d4088"
  , "EQ"
  , "PUSH2 tag_maxStore"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xe9cc4edd"
  , "EQ"
  , "PUSH2 tag_updateMax"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x5c34a245"
  , "EQ"
  , "PUSH2 tag_updateMin"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xac1f1f67"
  , "EQ"
  , "PUSH2 tag_setNonZero"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xc74962fa"
  , "EQ"
  , "PUSH2 tag_compareAndSwap"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xd3b9b05a"
  , "EQ"
  , "PUSH2 tag_initOnce"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x2dbeb1ba"
  , "EQ"
  , "PUSH2 tag_setIfGreater"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xb8df0e12"
  , "EQ"
  , "PUSH2 tag_bumpSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x7e5acdb6"
  , "EQ"
  , "PUSH2 tag_setIfLess"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x5ebc58db"
  , "EQ"
  , "PUSH2 tag_setIfBetween"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xbc0fcb79"
  , "EQ"
  , "PUSH2 tag_addIfBetween"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x8ba43d8f"
  , "EQ"
  , "PUSH2 tag_setIfNonZeroAndLess"
  , "JUMPI"
  , "PUSH4 0xc2311456"
  , "EQ"
  , "PUSH2 tag_bumpIfNonZero"
  , "JUMPI"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "tag_bumpIfNonZero:"
  , "PUSH2 ret_bumpIfNonZero"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_bumpIfNonZero"
  , "JUMP"
  , "ret_bumpIfNonZero:"
  , "STOP"
  , "tag_setIfNonZeroAndLess:"
  , "PUSH2 ret_setIfNonZeroAndLess"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setIfNonZeroAndLess"
  , "JUMP"
  , "ret_setIfNonZeroAndLess:"
  , "STOP"
  , "tag_addIfBetween:"
  , "PUSH2 ret_addIfBetween"
  , "PUSH1 0x64"
  , "CALLDATALOAD"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_addIfBetween"
  , "JUMP"
  , "ret_addIfBetween:"
  , "STOP"
  , "tag_setIfBetween:"
  , "PUSH2 ret_setIfBetween"
  , "PUSH1 0x64"
  , "CALLDATALOAD"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setIfBetween"
  , "JUMP"
  , "ret_setIfBetween:"
  , "STOP"
  , "tag_setIfLess:"
  , "PUSH2 ret_setIfLess"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setIfLess"
  , "JUMP"
  , "ret_setIfLess:"
  , "STOP"
  , "tag_bumpSlot:"
  , "PUSH2 ret_bumpSlot"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_bumpSlot"
  , "JUMP"
  , "ret_bumpSlot:"
  , "STOP"
  , "tag_setIfGreater:"
  , "PUSH2 ret_setIfGreater"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setIfGreater"
  , "JUMP"
  , "ret_setIfGreater:"
  , "STOP"
  , "tag_initOnce:"
  , "PUSH2 ret_initOnce"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_initOnce"
  , "JUMP"
  , "ret_initOnce:"
  , "STOP"
  , "tag_compareAndSwap:"
  , "PUSH2 ret_compareAndSwap"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_compareAndSwap"
  , "JUMP"
  , "ret_compareAndSwap:"
  , "STOP"
  , "tag_setNonZero:"
  , "PUSH2 ret_setNonZero"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setNonZero"
  , "JUMP"
  , "ret_setNonZero:"
  , "STOP"
  , "tag_updateMin:"
  , "PUSH2 ret_updateMin"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_updateMin"
  , "JUMP"
  , "ret_updateMin:"
  , "STOP"
  , "tag_updateMax:"
  , "PUSH2 ret_updateMax"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_updateMax"
  , "JUMP"
  , "ret_updateMax:"
  , "STOP"
  , "tag_maxStore:"
  , "PUSH2 ret_maxStore"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_maxStore"
  , "JUMP"
  , "ret_maxStore:"
  , "STOP"
  , "tag_guardedAddSlot:"
  , "PUSH2 ret_guardedAddSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_guardedAddSlot"
  , "JUMP"
  , "ret_guardedAddSlot:"
  , "STOP"
  , "tag_addSlot:"
  , "PUSH2 ret_addSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_addSlot"
  , "JUMP"
  , "ret_addSlot:"
  , "STOP"
  , "tag_setSlot:"
  , "PUSH2 ret_setSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setSlot"
  , "JUMP"
  , "ret_setSlot:"
  , "STOP"
  , "tag_getSlot:"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "SLOAD"
  , "PUSH0"
  , "MSTORE"
  , "PUSH1 0x20"
  , "PUSH0"
  , "RETURN"
  , "fn_setSlot:"
  , "SSTORE"
  , "JUMP"
  , "fn_addSlot:"
  , "SWAP1"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "JUMP"
  , "fn_guardedAddSlot:"
  , "SWAP1"
  , "PUSH0"
  , "SWAP2"
  , "DUP3"
  , "DUP3"
  , "GT"
  , "PUSH2 guardedAddSlot_ok"
  , "JUMPI"
  , "guardedAddSlot_check:"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 guardedAddSlot_revert"
  , "JUMPI"
  , "JUMP"
  , "guardedAddSlot_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "guardedAddSlot_ok:"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "PUSH0"
  , "PUSH2 guardedAddSlot_check"
  , "JUMP"
  , "fn_maxStore:"
  , "SWAP1"
  , "DUP3"
  , "SWAP1"
  , "DUP2"
  , "DUP2"
  , "GT"
  , "PUSH2 maxStore_then"
  , "JUMPI"
  , "maxStore_check:"
  , "GT"
  , "ISZERO"
  , "PUSH2 maxStore_else"
  , "JUMPI"
  , "maxStore_join:"
  , "POP"
  , "POP"
  , "JUMP"
  , "maxStore_else:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 maxStore_join"
  , "JUMP"
  , "maxStore_then:"
  , "DUP1"
  , "DUP4"
  , "SSTORE"
  , "PUSH2 maxStore_check"
  , "JUMP"
  , "fn_updateMax:"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "DUP2"
  , "DUP2"
  , "GT"
  , "PUSH2 updateMax_then"
  , "JUMPI"
  , "updateMax_check:"
  , "GT"
  , "ISZERO"
  , "PUSH2 updateMax_else"
  , "JUMPI"
  , "updateMax_join:"
  , "POP"
  , "POP"
  , "JUMP"
  , "updateMax_else:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 updateMax_join"
  , "JUMP"
  , "updateMax_then:"
  , "DUP1"
  , "DUP4"
  , "SSTORE"
  , "PUSH2 updateMax_check"
  , "JUMP"
  , "fn_updateMin:"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "DUP2"
  , "DUP2"
  , "LT"
  , "PUSH2 updateMin_then"
  , "JUMPI"
  , "updateMin_check:"
  , "LT"
  , "ISZERO"
  , "PUSH2 updateMin_else"
  , "JUMPI"
  , "updateMin_join:"
  , "POP"
  , "POP"
  , "JUMP"
  , "updateMin_else:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 updateMin_join"
  , "JUMP"
  , "updateMin_then:"
  , "DUP1"
  , "DUP4"
  , "SSTORE"
  , "PUSH2 updateMin_check"
  , "JUMP"
  , "fn_setNonZero:"
  , "SWAP1"
  , "DUP1"
  , "PUSH0"
  , "SWAP3"
  , "DUP4"
  , "DUP3"
  , "SUB"
  , "PUSH2 setNonZero_ok"
  , "JUMPI"
  , "setNonZero_check:"
  , "POP"
  , "POP"
  , "EQ"
  , "PUSH2 setNonZero_revert"
  , "JUMPI"
  , "JUMP"
  , "setNonZero_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setNonZero_ok:"
  , "SSTORE"
  , "DUP1"
  , "PUSH0"
  , "PUSH2 setNonZero_check"
  , "JUMP"
  , "fn_compareAndSwap:"
  , "SWAP1"
  , "SWAP2"
  , "DUP2"
  , "SLOAD"
  , "SWAP2"
  , "DUP4"
  , "DUP4"
  , "EQ"
  , "PUSH2 compareAndSwap_ok"
  , "JUMPI"
  , "compareAndSwap_check:"
  , "POP"
  , "POP"
  , "SUB"
  , "PUSH2 compareAndSwap_revert"
  , "JUMPI"
  , "JUMP"
  , "compareAndSwap_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "compareAndSwap_ok:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 compareAndSwap_check"
  , "JUMP"
  , "fn_initOnce:"
  , "PUSH0"
  , "SWAP2"
  , "DUP2"
  , "SLOAD"
  , "SWAP2"
  , "DUP4"
  , "DUP4"
  , "EQ"
  , "PUSH2 initOnce_ok"
  , "JUMPI"
  , "initOnce_check:"
  , "POP"
  , "POP"
  , "SUB"
  , "PUSH2 initOnce_revert"
  , "JUMPI"
  , "JUMP"
  , "initOnce_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "initOnce_ok:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 initOnce_check"
  , "JUMP"
  , "fn_setIfGreater:"
  , "DUP2"
  , "SWAP1"
  , "DUP4"
  , "DUP3"
  , "GT"
  , "PUSH2 setIfGreater_ok"
  , "JUMPI"
  , "setIfGreater_check:"
  , "POP"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 setIfGreater_revert"
  , "JUMPI"
  , "JUMP"
  , "setIfGreater_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfGreater_ok:"
  , "SSTORE"
  , "DUP1"
  , "PUSH0"
  , "PUSH2 setIfGreater_check"
  , "JUMP"
  , "fn_bumpSlot:"
  , "PUSH1 0x01"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "JUMP"
  , "fn_setIfLess:"
  , "DUP2"
  , "SWAP1"
  , "DUP4"
  , "DUP3"
  , "LT"
  , "PUSH2 setIfLess_ok"
  , "JUMPI"
  , "setIfLess_check:"
  , "POP"
  , "POP"
  , "LT"
  , "ISZERO"
  , "PUSH2 setIfLess_revert"
  , "JUMPI"
  , "JUMP"
  , "setIfLess_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfLess_ok:"
  , "SSTORE"
  , "DUP1"
  , "PUSH0"
  , "PUSH2 setIfLess_check"
  , "JUMP"
  , "fn_setIfBetween:"
  , "SWAP1"
  , "DUP1"
  , "SWAP3"
  , "SWAP4"
  , "SWAP2"
  , "DUP5"
  , "DUP3"
  , "GT"
  , "PUSH2 setIfBetween_outer_ok"
  , "JUMPI"
  , "setIfBetween_outer_check:"
  , "POP"
  , "POP"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 setIfBetween_revert_outer"
  , "JUMPI"
  , "JUMP"
  , "setIfBetween_revert_outer:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfBetween_outer_ok:"
  , "DUP3"
  , "DUP3"
  , "LT"
  , "PUSH2 setIfBetween_inner_ok"
  , "JUMPI"
  , "setIfBetween_inner_check:"
  , "POP"
  , "LT"
  , "ISZERO"
  , "PUSH2 setIfBetween_revert_inner"
  , "JUMPI"
  , "PUSH0"
  , "DUP2"
  , "DUP2"
  , "PUSH2 setIfBetween_outer_check"
  , "JUMP"
  , "setIfBetween_revert_inner:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfBetween_inner_ok:"
  , "SSTORE"
  , "DUP2"
  , "PUSH0"
  , "PUSH2 setIfBetween_inner_check"
  , "JUMP"
  , "fn_addIfBetween:"
  , "SWAP3"
  , "SWAP1"
  , "SWAP2"
  , "SWAP3"
  , "DUP4"
  , "DUP4"
  , "GT"
  , "PUSH2 addIfBetween_outer_ok"
  , "JUMPI"
  , "addIfBetween_outer_check:"
  , "POP"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 addIfBetween_revert_outer"
  , "JUMPI"
  , "JUMP"
  , "addIfBetween_revert_outer:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "addIfBetween_outer_ok:"
  , "DUP2"
  , "DUP4"
  , "LT"
  , "PUSH2 addIfBetween_inner_ok"
  , "JUMPI"
  , "addIfBetween_inner_check:"
  , "POP"
  , "DUP2"
  , "LT"
  , "ISZERO"
  , "PUSH2 addIfBetween_revert_inner"
  , "JUMPI"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 addIfBetween_outer_check"
  , "JUMP"
  , "addIfBetween_revert_inner:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "addIfBetween_inner_ok:"
  , "DUP3"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "PUSH0"
  , "PUSH2 addIfBetween_inner_check"
  , "JUMP"
  , "fn_setIfNonZeroAndLess:"
  , "SWAP2"
  , "DUP2"
  , "PUSH0"
  , "SWAP3"
  , "SWAP4"
  , "DUP3"
  , "DUP3"
  , "LT"
  , "DUP5"
  , "DUP4"
  , "EQ"
  , "ISZERO"
  , "AND"
  , "PUSH2 setIfNonZeroAndLess_ok"
  , "JUMPI"
  , "setIfNonZeroAndLess_check:"
  , "POP"
  , "LT"
  , "SWAP2"
  , "EQ"
  , "ISZERO"
  , "AND"
  , "ISZERO"
  , "PUSH2 setIfNonZeroAndLess_revert"
  , "JUMPI"
  , "JUMP"
  , "setIfNonZeroAndLess_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfNonZeroAndLess_ok:"
  , "SSTORE"
  , "DUP3"
  , "PUSH0"
  , "PUSH2 setIfNonZeroAndLess_check"
  , "JUMP"
  , "fn_bumpIfNonZero:"
  , "PUSH0"
  , "SWAP1"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "SUB"
  , "PUSH2 bumpIfNonZero_ok"
  , "JUMPI"
  , "bumpIfNonZero_check:"
  , "SLOAD"
  , "EQ"
  , "PUSH2 bumpIfNonZero_revert"
  , "JUMPI"
  , "JUMP"
  , "bumpIfNonZero_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "bumpIfNonZero_ok:"
  , "PUSH1 0x01"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "DUP2"
  , "SSTORE"
  , "PUSH2 bumpIfNonZero_check"
  , "JUMP"
  ]

def pretty (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

end DumbContracts.EvmAsm
