namespace DumbContracts.EvmAsm

-- Minimal EVM asm emitter (same calling convention as Yul).

def directProgramAsm : List String :=
  [ "entry:"
  , "PUSH0"
  , "CALLDATALOAD"
  , "PUSH1 0xe0"
  , "SHR"
  , "DUP1"
  , "PUSH4 0x7eba7ba6"
  , "EQ"
  , "PUSH2 tag_getSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xf2c298be"
  , "EQ"
  , "PUSH2 tag_setSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x02222aec"
  , "EQ"
  , "PUSH2 tag_addSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x49f583e3"
  , "EQ"
  , "PUSH2 tag_guardedAddSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xb61d4088"
  , "EQ"
  , "PUSH2 tag_maxStore"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xac1f1f67"
  , "EQ"
  , "PUSH2 tag_setNonZero"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xc74962fa"
  , "EQ"
  , "PUSH2 tag_compareAndSwap"
  , "JUMPI"
  , "PUSH4 0x2dbeb1ba"
  , "EQ"
  , "PUSH2 tag_setIfGreater"
  , "JUMPI"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "tag_setIfGreater:"
  , "PUSH2 ret_setIfGreater"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setIfGreater"
  , "JUMP"
  , "ret_setIfGreater:"
  , "STOP"
  , "tag_compareAndSwap:"
  , "PUSH2 ret_compareAndSwap"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_compareAndSwap"
  , "JUMP"
  , "ret_compareAndSwap:"
  , "STOP"
  , "tag_setNonZero:"
  , "PUSH2 ret_setNonZero"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setNonZero"
  , "JUMP"
  , "ret_setNonZero:"
  , "STOP"
  , "tag_maxStore:"
  , "PUSH2 ret_maxStore"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_maxStore"
  , "JUMP"
  , "ret_maxStore:"
  , "STOP"
  , "tag_guardedAddSlot:"
  , "PUSH2 ret_guardedAddSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_guardedAddSlot"
  , "JUMP"
  , "ret_guardedAddSlot:"
  , "STOP"
  , "tag_addSlot:"
  , "PUSH2 ret_addSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_addSlot"
  , "JUMP"
  , "ret_addSlot:"
  , "STOP"
  , "tag_setSlot:"
  , "PUSH2 ret_setSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH2 fn_setSlot"
  , "JUMP"
  , "ret_setSlot:"
  , "STOP"
  , "tag_getSlot:"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "SLOAD"
  , "PUSH0"
  , "MSTORE"
  , "PUSH1 0x20"
  , "PUSH0"
  , "RETURN"
  , "fn_setSlot:"
  , "SSTORE"
  , "JUMP"
  , "fn_addSlot:"
  , "SWAP1"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "JUMP"
  , "fn_guardedAddSlot:"
  , "SWAP1"
  , "PUSH0"
  , "SWAP2"
  , "DUP3"
  , "DUP3"
  , "GT"
  , "PUSH2 guardedAddSlot_ok"
  , "JUMPI"
  , "guardedAddSlot_check:"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 guardedAddSlot_revert"
  , "JUMPI"
  , "JUMP"
  , "guardedAddSlot_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "guardedAddSlot_ok:"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "PUSH0"
  , "PUSH2 guardedAddSlot_check"
  , "JUMP"
  , "fn_maxStore:"
  , "SWAP1"
  , "DUP3"
  , "SWAP1"
  , "DUP2"
  , "DUP2"
  , "GT"
  , "PUSH2 maxStore_then"
  , "JUMPI"
  , "maxStore_check:"
  , "GT"
  , "ISZERO"
  , "PUSH2 maxStore_else"
  , "JUMPI"
  , "maxStore_join:"
  , "POP"
  , "POP"
  , "JUMP"
  , "maxStore_else:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 maxStore_join"
  , "JUMP"
  , "maxStore_then:"
  , "DUP1"
  , "DUP4"
  , "SSTORE"
  , "PUSH2 maxStore_check"
  , "JUMP"
  , "fn_setNonZero:"
  , "SWAP1"
  , "DUP1"
  , "PUSH0"
  , "SWAP3"
  , "DUP4"
  , "DUP3"
  , "SUB"
  , "PUSH2 setNonZero_ok"
  , "JUMPI"
  , "setNonZero_check:"
  , "POP"
  , "POP"
  , "EQ"
  , "PUSH2 setNonZero_revert"
  , "JUMPI"
  , "JUMP"
  , "setNonZero_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setNonZero_ok:"
  , "SSTORE"
  , "DUP1"
  , "PUSH0"
  , "PUSH2 setNonZero_check"
  , "JUMP"
  , "fn_compareAndSwap:"
  , "SWAP1"
  , "SWAP2"
  , "DUP2"
  , "SLOAD"
  , "SWAP2"
  , "DUP4"
  , "DUP4"
  , "EQ"
  , "PUSH2 compareAndSwap_ok"
  , "JUMPI"
  , "compareAndSwap_check:"
  , "POP"
  , "POP"
  , "SUB"
  , "PUSH2 compareAndSwap_revert"
  , "JUMPI"
  , "JUMP"
  , "compareAndSwap_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "compareAndSwap_ok:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH2 compareAndSwap_check"
  , "JUMP"
  , "fn_setIfGreater:"
  , "DUP2"
  , "SWAP1"
  , "DUP4"
  , "DUP3"
  , "GT"
  , "PUSH2 setIfGreater_ok"
  , "JUMPI"
  , "setIfGreater_check:"
  , "POP"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH2 setIfGreater_revert"
  , "JUMPI"
  , "JUMP"
  , "setIfGreater_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "setIfGreater_ok:"
  , "SSTORE"
  , "DUP1"
  , "PUSH0"
  , "PUSH2 setIfGreater_check"
  , "JUMP"
  ]

def pretty (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

end DumbContracts.EvmAsm
